### ISSUE TITLE
Missing javadoc

### ISSUE THREAD

**Issue by leader80** [claeis/ilivalidator#1]
Hi Claeis,

I would like to help you developing the project, do you mind putting some javadoc in your source code?

Best regards
G.

**Comment by claeis** [comment]
The project ilivalidator is just a frontent: cmdline and GUI (and a high-level API).

The low-level API, the one used by ili2pg, is in the project iox-ili, which is base on interfaces defined in project iox-api.

**Comment by claeis** [comment]
added javadocs
