### ISSUE TITLE
Mandatory constrained not evaluated

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#102]
According to the model `GrundstuecksArt` is not mandatory:

`    CLASS Grundstueck(ABSTRACT) =`
  `    Flaechenmass : GB2AV.Flaeche;`
  `    GrundstueckArt : GB2AV.GrundstuecksArtAV;`

The extended class `Liegenschaft` defines: 

`MANDATORY CONSTRAINT GrundstueckArt==#Liegenschaft;`

Does this mean that if there is a value, it has to be `#Liegenschaft` but it still can be empty since it is not mandatory?

**Comment by claeis** [comment]
Yes, this is/was clarified in the spec 2.4: 

> Ist eine Konsistenzbedingung (MANDATORY CONSTRAINT) nicht berechenbar (weil z.B. ein Attribut beteiligt ist, dessen Wert undefiniert ist, oder der Divisor 0 beträgt) so gilt die Konsistenzbedingung für das aktuelle Objekt als erfüllt.
