### ISSUE TITLE
integration_geodienste.ch KbS: Error: compiler failed

### ISSUE THREAD

**Issue by VeraDiaz** [claeis/ilivalidator#104]
Validating a KbS-File on integration.geodienste.ch I get the following error:
Error: /home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte/KbS_LV03_V1_3.ili:6:The name of the model conflicts with MODEL KbS_Basis_V1_3. Model names must be unique; please use a different name.
Error: compiler failed

When I validate the same file using https://interlis2.ch/ilivalidator/,
 validation is done without error.
 
[sz.zip](https://github.com/claeis/ilivalidator/files/1707142/sz.zip)

**Comment by beistehen** [comment]
This is a compiler error that refers to the INTERLIS model (.ili), not the data itself.

As https://integration.geodienste.ch/ has restricted access, I can not reproduce the error. I guess on geodienste.ch the models are stored locally and on interlis2.ch they are fetched from the repositories. If you can get access to the .ili file mentioned in the error then you can post it here and we can futher analyse the model.

Regards,
Stefan

**Comment by VeraDiaz** [comment]
[KbS_V1_3.zip](https://github.com/claeis/ilivalidator/files/1707525/KbS_V1_3.zip)
This is the model that's published on models.geo.admin.ch.

thanks and regards,
Vera

**Comment by dkottmann** [comment]
On integration.geodienste.ch we run ilivalidator v 1.6.0

ili on integration.geodienste.ch:
[kataster_belasteter_standorte_model.zip](https://github.com/claeis/ilivalidator/files/1707557/kataster_belasteter_standorte_model.zip)

**Comment by claeis** [comment]
pls add a log of the run that fails

**Comment by beistehen** [comment]
It looks like on geodienste.ch the original .ili file from models.geo.admin.ch is splitted in two files, one file per coordinate reference system (LV03, LV95). But the base model _KbS_Basis_V1_3_ was duplicated by this process; it is present in both .ili files.

From the compiler's perspective when crawling through the local repository at geodienste.ch, the base model _KbS_Basis_V1_3_ shows up twice, which raises the error.

On models.geo.admin.ch both CRS-specific models as well as the base model are in the same .ili file. So no duplicate exist.

I suggest using the single file version from models.geo.admin.ch if there is no other reason to split the files.

Regards,
Stefan

**Comment by dkottmann** [comment]
Thanks for your help! 

In previous versions of ilivalidator (<1.6.0) respecitvely ili2c (<3.7.6) we did not have this issue on geodienste.ch. Models for LV03 and LV95 currently need to be in separate Files on geodienste.ch. 

I changed ili on integration.geodienste.ch to this: 
[kataster_belasteter_standorte_model.zip](https://github.com/claeis/ilivalidator/files/1710055/kataster_belasteter_standorte_model.zip)

Now validation with provided data works fine, see log: 
[KbS_SZ_geodienste.ch.log](https://github.com/claeis/ilivalidator/files/1710046/KbS_SZ_geodienste.ch.log)

There ist one warning, though.
> Warning: model Grundwasserqualitaet_LV95_V1: duplicate version without precursor; version 2018-01-23 ignored

**Comment by claeis** [comment]
The warning indicates that there is still a duplicate model (and therefore the one chosen an act of randomness).

**Comment by dkottmann** [comment]
- Duplicate has not been created by geodienste.ch. Model Grundwasserqualitaet_LV95_V1 is not included in modeldir an has nothing to do with KbS... (no IMPORTS). Why is ili2c looking up this model in the process of validating data in KbS_LV95_V1_3? 
- could it be an issue with .ilicache on geodienste.ch? 
- could it be an issue on https://models.geo.admin.ch?

**Comment by claeis** [comment]
pls add the log

**Comment by dkottmann** [comment]
```
  Info: ilivalidator-1.6.0-5e18cf6587dae29c6452544e5667a1a2edc36574
Info: ili2c-4.7.6-20171229
Info: iox-ili-1.20.1-2c7ee543644f43e2b404e08f5c9d06870f700825
Info: maxMemory 932352 KB
Info: dataFile </tmp/ili_agg/kataster_belasteter_standorte/sz/LV95_1518159966/kbs_testdatensatz.xtf>
Info: pluginFolder </opt/ilivalidator/plugins>
Info: ilidirs </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte;http://models.interlis.ch/>
Info: lookup model <Localisation_V1> in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: lookup model <Localisation_V1> in repository <http://models.interlis.ch/>
Info: lookup model <Localisation_V1> in repository <http://models.geo.admin.ch>
Warning: model Grundwasserqualitaet_LV95_V1: duplicate version without precursor; version 2018-01-23 ignored
Info: lookup model <KbS_Basis_V1_3> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: lookup model <CoordSys> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Units> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <KbS_LV03_V1_3> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: lookup model <KbS_LV95_V1_3> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte>
Info: ilifile </home/rails/.ilicache/models.interlis.ch/refhb23/Units-20120220.ili>
Info: ilifile </home/rails/.ilicache/models.geo.admin.ch/CH/CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile </home/rails/.ilicache/models.interlis.ch/refhb23/CoordSys-20151124.ili>
Info: ilifile </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte/KbS_Basis_V1_3.ili>
Info: ilifile </home/rails/.ilicache/models.geo.admin.ch/CH/CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte/KbS_LV03_V1_3.ili>
Info: ilifile </home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte/KbS_LV95_V1_3.ili>
Info: validate data...
Info: assume unknown/external objects
Info: only multiplicity validation relaxable
Info: first validation pass...
Info: second validation pass...
Info: validate mandatory constraint KbS_LV95_V1_3.Belastete_Standorte.Belasteter_Standort.Constraint1...
Info: validate mandatory constraint KbS_LV95_V1_3.Belastete_Standorte.Belasteter_Standort.Constraint2...
Info: validate mandatory constraint KbS_LV95_V1_3.Belastete_Standorte.Belasteter_Standort.Constraint3...
Info: validate mandatory constraint KbS_LV95_V1_3.Belastete_Standorte.Belasteter_Standort.Constraint4...
Info: validate target of role KbS_LV95_V1_3.Belastete_Standorte.ZustaendigkeitKatasterBelasteter_Standort.ZustaendigkeitKataster...
Info: validate multiplicity of role KbS_LV95_V1_3.Belastete_Standorte.ZustaendigkeitKatasterBelasteter_Standort.ZustaendigkeitKataster...
Info: validate mandatory constraint LocalisationCH_V1.LocalisedText.Constraint1...
Info: validate multiplicity of role KbS_LV95_V1_3.Belastete_Standorte.ZustaendigkeitKatasterBelasteter_Standort.Belasteter_Standort...
Info: /tmp/ili_agg/kataster_belasteter_standorte/sz/LV95_1518159966/kbs_testdatensatz.xtf: KbS_LV95_V1_3.Belastete_Standorte BID=bs1518073201
Info: ?     2 objects in CLASS KbS_LV95_V1_3.Belastete_Standorte.Belasteter_Standort
Info: ?     1 objects in CLASS KbS_LV95_V1_3.Belastete_Standorte.ZustaendigkeitKataster
Info: ...validation done
```

**Comment by beistehen** [comment]
I guess it is a repository error in models.geo.admin.ch. Hard to check as this repository is not statically accessible (.ili files not downloadable using wget because of Javascript). Or am I missing something?

The question of @dkottmann is understandable: why is ili2c checking the repository for errors with models that are not used in the dataset ilivalidator is checking? This error should not show up in the validation log for a completely unrelated dataset, it is confusing.

@claeis coud this general repository check be suppressed when invoking ili2c from out of ilivalidator?

Gruss
Stefan

**Comment by claeis** [comment]
no, the check/warning is there to enforce valid repositories and is executed on all accessed repositories. 

I just checked models.geo.admin.ch and it seems ok. (You can enforce an update of your local cache by deleting $HOME/.ilicache)

What files do you have in ```/home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte```?

**Comment by dkottmann** [comment]
> I just checked models.geo.admin.ch and it seems ok. (You can enforce an update of your local cache by deleting $HOME/.ilicache)

I just heard that ilimodels.xml of has been corrected on repository models.geo.admin.ch yesterday evening. So it seems, that this warning is related to the cache. Shouldn't ili2c update the local cache automatically if there are changes in repositories? If not, is it recommended to flush the cache after + before every ilivalidator program?  

> What files do you have in /home/rails/geodienste-config/current/ili_agg/ili/kataster_belasteter_standorte?

see also link above, or here: 
[kataster_belasteter_standorte_model.zip](https://github.com/claeis/ilivalidator/files/1710055/kataster_belasteter_standorte_model.zip)

**Comment by claeis** [comment]
```$HOME/.ilicache``` is updated automatically and regularly.

```ilisite.xml``` and ```ilimodels.xml``` are updated after 24h (of last update).

```.ili```-files are updated after 7 days (of last update) or earlier, if the md5 checksum from the  ```ilimodels.xml``` no longer matches.

**Comment by dkottmann** [comment]
OK, then this warning should disappear this evening by itself, if it is really caused by ilimodels.xml.

**Comment by dkottmann** [comment]
confirmed, warning cannot be reproduced anymore.
