### ISSUE TITLE
Directory ilimodels not recognized

### ISSUE THREAD

**Issue by p1d1d1** [claeis/ilivalidator#106]
As in the title versions 1.6 and 1.7 require a folder %ILI_DIR instead of ilimodels

**Comment by claeis** [comment]
Please add a detailed log (--trace)

**Comment by p1d1d1** [comment]
[log1.txt](https://github.com/claeis/ilivalidator/files/1761988/log1.txt) ili file under folder ilimodels 
[log2.txt](https://github.com/claeis/ilivalidator/files/1761989/log2.txt) ili file under folder %ILI_DIR

**Comment by renato1987** [comment]
Hi p1d1d1

Thank you for your request.

there is no placeholder: %ILI_DIR.
valid placeholders are %ITF_DIR or %JAR_DIR.

see documentation of ilivalidator:

https://github.com/claeis/ilivalidator/blob/master/docs/ilivalidator.rst


Option: --modeldir path
- Path with folders of Interlis model files.
- Multiple entries are separated by semicolon (';').
- Might contain "http:" URLs which should contain model repositories.
- Might include placeholders ITF_DIR or JAR_DIR.

default placeholder:
%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels

I hope that your request is answered.

**Comment by p1d1d1** [comment]
@renato1987 you write:

> default placeholder:
%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels

So I assume that if I put the model in a folder ilimodels I can run:

`java -jar ilivalidator.jar path/to/data.xtf`

and it should work. Is that correct?

**Comment by p1d1d1** [comment]
@renato1987 

I did a further test:

1) Put the model in the folder "ilimodels"
2) Run `java -jar ilivalidator-1.7.0.jar data.xtf.` --> non working

If you have a look at the attached logfile:

`Info: ilidirs <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels>`
`...`
`Info: lookup model <TestSuite> in repository <C:\LegacySW\ilivalidator\ilivalidator-1.7.0\%JAR_DIR\ilimodels>`
`Warning:` Folder C:\LegacySW\ilivalidator\ilivalidator-1.7.0\%JAR_DIR\ilimodels doesn't exist; ignored` 

It is looking for a folder with name "%JAR_DIR". And in fact it works if I put the model in a folder with name "%JAR_DIR\ilimodels". I get from the log:

`Info: ilifile <C:\LegacySW\ilivalidator\ilivalidator-1.7.0\%JAR_DIR\ilimodels\TestSuite.ili>`

[log.log](https://github.com/claeis/ilivalidator/files/1767784/log.log)

**Comment by beistehen** [comment]
Ciao Pasquale

While staring at the code I might have found the problem. Can you rename `ilivalidator-1.7.0.jar` to `ilivalidator.jar` and check whether the problem persists?

Regards,
Stefan

@renato1987: it looks like in `Main.getAppHome()` the constant `APP_JAR` is used, which makes the function check only for the filename `ilivalidator.jar` but fails to return the current path of the jar file if it has a different name.

**Comment by renato1987** [comment]
Hi p1d1d1
thanks for your examples.
i will take a look to this Problems.

**Comment by renato1987** [comment]
@p1d1d1, @beistehen:
Hi
In the next release it should work to run ilivalidator.jar, no matter what the version is.
The example of p1d1d1: java -jar ilivalidator.jar path/to/data.xtf will also run correct in the next release.

**Comment by p1d1d1** [comment]
Stefan (@beistehen) just to confirm that by renaming  ilivalidator-1.7.0.jar to ilivalidator.jar it works as expected.

**Comment by p1d1d1** [comment]
@renato1987 @claeis version 1.8.0 is working via CLI, but not in GUI.

In Tools-->Model Repositories I have: %ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels
