### ISSUE TITLE
Check constraint on areAreas()

### ISSUE THREAD

**Issue by pasimo** [claeis/ilivalidator#109]
Concerning a warning the following constraint is not yet checked:
SET CONSTRAINT areAreas(ALL, >> TIN, >> Triangulation->Triangle);

It would be great, if this check would be implemented for a future release:
https://models.geo.admin.ch/BAZL/CadastreOfObstacleLimitationSurfaces_V1.ili

Kind regards
P. Imoberdorf

**Comment by claeis** [comment]
Which ilivalidator version?
Can you add the log?

**Comment by claeis** [comment]
Why did you define your own areAreas(), instead of using INTERLIS.areAreas()?

**Comment by pasimo** [comment]
Info: ilivalidator-1.8.1-2748b46e6be0e4c6ce91de0e889217f2cc0b5885
Info: ili2c-4.7.7-20180208
Info: iox-ili-1.20.4-3bec640e2cb288397dc8f371dab21e91dfe43b36
Info: maxMemory 1837056 KB
Info: dataFile <U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output\20180221_HBK-Balzers-Einreichung-2-ohne-FATO.xtf>
Info: ilidirs <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels>
Info: httpProxyHost <lf00002a.adb.intra.admin.ch>
Info: httpProxyPort <8080>
Info: lookup model <WithOneState_V1> in repository <U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output>
Info: lookup model <WithOneState_V1> in repository <http://models.interlis.ch/>
Info: lookup model <WithOneState_V1> in repository <C:\APSLocalData\ClientData\Interlis\ilivalidator-1.8.1/ilimodels>
Info: lookup model <WithOneState_V1> in repository <http://models.geo.admin.ch>
Info: lookup model <CoordSys> 2.3 in repository <U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Units> 2.3 in repository <U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <C:\APSLocalData\ClientData\Interlis\ilivalidator-1.8.1/ilimodels>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <CadastreOfObstacleLimitationSurfaces_V1> 2.3 in repository <U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output>
Info: lookup model <CadastreOfObstacleLimitationSurfaces_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CadastreOfObstacleLimitationSurfaces_V1> 2.3 in repository <C:\APSLocalData\ClientData\Interlis\ilivalidator-1.8.1/ilimodels>
Info: lookup model <CadastreOfObstacleLimitationSurfaces_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: ilifile <C:\Users\U80812270\.ilicache\models.interlis.ch\refhb23\Units-20120220.ili>
Info: ilifile <C:\Users\U80812270\.ilicache\models.interlis.ch\refhb23\CoordSys-20151124.ili>
Info: ilifile <C:\Users\U80812270\.ilicache\models.geo.admin.ch\CH\CHBase_Part5_MODIFICATIONINFO_20110830.ili>
Info: ilifile <C:\Users\U80812270\.ilicache\models.geo.admin.ch\CH\CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile <C:\Users\U80812270\.ilicache\models.geo.admin.ch\BAZL\CadastreOfObstacleLimitationSurfaces_V1.ili>
Info: validate data...
Info: assume unknown/external objects
Info: first validation pass...
Info: validate unique constraint CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsCadastre.Constraint1...
Info: validate unique constraint CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.Ols.Constraint1...
Info: second validation pass...
Info: validate target of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsLineElement.OlsR...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsLineElement.OlsR...
Info: validate target of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsRestrictivePart.OlsR...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsRestrictivePart.OlsR...
Info: validate mandatory constraint WithLatestModification_V1.ModInfo.Constraint1...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.CadastreObstacleArea.ObstacleArea...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsSpatialReference.OlsR...
Info: validate target of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsSpatialReference.SpatialReference...
Info: validate target of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsSpatialReference.OlsR...
Info: validate target of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.CadastreObstacleArea.Cadastre...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsLineElement.LineElement...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.CadastreObstacleArea.Cadastre...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsSpatialReference.SpatialReference...
Info: validate multiplicity of role CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsRestrictivePart.RestrictivePart...
Info: validate set constraint CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.Ols.Constraint2...
Info: validate plausibility constraint CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.Ols.Constraint2...
Warning: line 112: CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.Ols: tid Takeoff_climb_surface_heli: Function in set constraint CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.Ols.Constraint2 is not yet implemented.
Info: validate AREA CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.RestrictiveArea.Area2D...
Info: U:\GIS\INFOPLAN\Produktion_BAZL\HBK\Balzers_LSXB\3_HBK_Freigabe\OLS-Daten_INTERLIS\03-Output\20180221_HBK-Balzers-Einreichung-2-ohne-FATO.xtf: CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification BID=b001
Info:       1 objects in CLASS CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.Ols
Info:       1 objects in CLASS CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsCadastre
Info:     105 objects in CLASS CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsLine
Info:       1 objects in CLASS CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.OlsSpatialReference
Info:       1 objects in CLASS CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.ReferencePoint
Info:       2 objects in CLASS CadastreOfObstacleLimitationSurfaces_V1.CadastreOfObstacleLimitationSurfaces_WithLatestModification.RestrictiveArea
Info: ...validation done

Von: claeis <notifications@github.com>
Gesendet: Freitag, 13. April 2018 16:48
An: claeis/ilivalidator <ilivalidator@noreply.github.com>
Cc: Imoberdorf Pascal BAZL <pascal.imoberdorf@bazl.admin.ch>; Author <author@noreply.github.com>
Betreff: Re: [claeis/ilivalidator] Check constraint on areAreas() (#109)


Which ilivalidator version?
Can you add the log?

**Comment by pasimo** [comment]
Good question. We didn’t realize, that this might be possible. Does it matter?

Von: claeis <notifications@github.com>
Gesendet: Freitag, 13. April 2018 16:54
An: claeis/ilivalidator <ilivalidator@noreply.github.com>
Cc: Imoberdorf Pascal BAZL <pascal.imoberdorf@bazl.admin.ch>; Author <author@noreply.github.com>
Betreff: Re: [claeis/ilivalidator] Check constraint on areAreas() (#109)


Why did you define your own areAreas(), instead of using INTERLIS.areAreas()?
