### ISSUE TITLE
Open transferfile: improve fileselector

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#120]
Im Dialogfenser "Transferdatei öffnen" kann als Dateityp nebst Alle Dateien, *.xtf, *.itf und *.xml gewählt werden. Sehr oft werden *.xtf und *.xml zusammen verwendet (z.B. bei allen Test mit externen Katalogen). Es sollte eine Auswahlt *.xtf und *.xml zusammen gewählt werden können. Man könnte diese Auswahl sogar als Default setzen, weil am meisten verwendet.

**Comment by claeis** [comment]
requires claeis/ehibasics#2

**Comment by claeis** [comment]
1.9.3
