### ISSUE TITLE
--xtflog not reporting errors

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#122]
- errors are not reported in the xtf (attached xtf has some duplicate coords)
- `illegal value null for ...` messagens in the terminal

v1.9.2
[npl_niederbuchsiten_vor_OP.xtf.zip](https://github.com/claeis/ilivalidator/files/2267248/npl_niederbuchsiten_vor_OP.xtf.zip)

**Comment by claeis** [comment]
see #124 for second bullet

**Comment by claeis** [comment]
#124 fixes also the first bullet

**Comment by claeis** [comment]
1.9.3
