### ISSUE TITLE
suggestion: option / TOML to disable rounding

### ISSUE THREAD

**Issue by dkottmann** [claeis/ilivalidator#125]
- introduction of new option '--disableRounding' 
- allow TOML configuration to disable rounding or force better accuracy of the model / data

these features would allow a workaround for #123 / #111 as long as the necessary corrections are not applied by the data owner

**Comment by beistehen** [comment]
I wonder whether it is wise to have a switch to disable every option that is not so convenient. We will end up with pretended "error free" data but it is only because all the quality checks have been disabled...

**Comment by claeis** [comment]
1.9.3
