### ISSUE TITLE
not a valid OID

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ilivalidator#135]
With the latest version (1.9.3) the BID/TID value syntax gets validated.
Is that the reason why my OIDs are not valid any more?
What can I do to eliminate this error?
Here an extract of the logfile:
Error: line 5: PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich: tid {bcb7a0da-8260-4b31-8b66-73e341010ac1}: value <{bcb7a0da-8260-4b31-8b66-73e341010ac1}> is not a valid OID
Error: line 6: PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich: tid {306fcc6a-4752-443e-b1cc-1f4c7b816da2}: value <{306fcc6a-4752-443e-b1cc-1f4c7b816da2}> is not a valid OID
Error: line 7: PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich: tid {6eb2b7f8-7935-4a3c-b2d4-32a181617bef}: value <{6eb2b7f8-7935-4a3c-b2d4-32a181617bef}> is not a valid OID
Error: line 8: PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich: tid {c200b8fb-ac90-4bbd-bfab-9e3a5c3b0694}: value <{c200b8fb-ac90-4bbd-bfab-9e3a5c3b0694}> is not a valid OID
And so on...

**Comment by claeis** [comment]
Yes, the syntax of the TID/BID is now validated. see #129.
Fix the export/transfer file or --disableValidation

**Comment by claeis** [comment]
The ```{``` and ```}``` is wrong.

**Comment by kuhnpa** [comment]
Thanks. That was the hint I needed.

**Comment by kuhnpa** [comment]
I'm running into the same error message again with ilivalidator 1.11.0 with a different dataset.
Error: line 5: Hazard_Mapping_LV95_V1_2.hazard_mapping.assessment_area: tid 80ebcd0b-3c82-4904-bd98-f921d6b46569: value <80ebcd0b-3c82-4904-bd98-f921d6b46569> is not a valid OID

As in the changelog for v 1.10.0 these two changes are noted:
- validate UUID if used as BID
- validate TEXT OID

What does this new validation mean?
The OID looks good to me.

**Comment by claeis** [comment]
- validate TEXT OID means: a BID/TID values must  match the rule `( Letter | Digit | '_' ) { Letter | Digit | '_' | '-' | '.' }`
- validate UUID if used as BID means: if the TOPIC has `BASKET OID AS INTERLIS.UUIDOID` the BID value must math the rules of a UUID

**Comment by claeis** [comment]
Ch. 2.8.9 Wertebereiche von Objektidentifikationen

> OID-Werte von textlichen OID-Wertebereichen müssen die Regeln des XML-ID-Typs erfüllen: erstes Zeichen muss Buchstabe oder Unterstrich sein, dann folgen Buchstaben, Ziffern, Punkte, Minuszeichen,
Unterstriche

**Comment by claeis** [comment]
The MODEL Hazard_Mapping_LV95_V1_2 defines defines a TEXT OID `haz_map_oid = OID TEXT*120;`

**Comment by kuhnpa** [comment]
Thank you very much.
