### ISSUE TITLE
not valid OID

### ISSUE THREAD

**Issue by tdco006** [claeis/ilivalidator#137]
With the latest version (1.9.3) the BID/TID value syntax gets validated.
For a particular case we have some TID in text format containing the parentheses, which according to the Intelis reference manual would be possible.
We are aware of the fact that a TID should be strictly a unique and possibly numerical value, but in these situations we need to be able to trace the data in management.
How did Mr. Ziegler Stefano, the error probably resides in the Ch. Interlis. Iox_j. Validator package in the Regex function or you can't actually use parentheses and it doesn't show up from the manual.
Thank you

**Comment by beistehen** [comment]
No parantheses (neither '()' nor '{}' nor '[]' are allowed as TID/BID according to the INTERLIS reference manual, section 3.3.1 (see also #129 and #135) .
Regards, Stefan (not Ziegler ;-)
