### ISSUE TITLE
Wrong/confusing info message concerning known objects

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#141]
Without using `--allObjectsAccessible` there is the following info message:

`Info: assume unknown/external objects`

When using `--allObjectsAccessible` there is no such message. From my point of view, it should be vice-versa?

**Comment by claeis** [comment]
I assume, a user expects that everything gets checked/validated. However, with EXTERNAL objects (objects that exist, but are not known to the validator), some checks have to be relaxed (I consider this as a deviation from the normal behavior, and therefore log this).

**Comment by edigonzales** [comment]
Stupid me. I just misread the info message. But some minor detail: Shouldn't it be `assume unknown external objects`?
