### ISSUE TITLE
validate TEXT oid (RAt_T11f)

### ISSUE THREAD

**Issue by claeis** [claeis/ilivalidator#150]
```
CLASS
      TextID : OID TEXT*34;
```
invalid value
```
		<TextID OID="1abcdefghilmno16"/> 
```

**Comment by alideniz1986** [comment]
OID-Werte von textlichen OID-Wertebereichen müssen die Regeln des XML-ID-Typs erfüllen: erstes Zeichen
muss Buchstabe oder Unterstrich sein, dann folgen Buchstaben, Ziffern, Punkte, Minuszeichen,
Unterstriche; keine Doppelpunkte (!), siehe www.w3.org/TR/REC-xml
