### ISSUE TITLE
config file - qualified names of roles in INTERLIS1

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#157]
When refererring to a relation between two tables in a config file (.toml), what are the building rules to specify the qualified name of the role?

# Example
Having the following model:
```
MODEL M =
  TOPIC T =
    TABLE A =
      AttA1: TEXT*20;
    END A;

    TABLE B = 
      AttB1: TEXT*10;
      AttB2: -> A;
      AttB3: -> A;
    END B;
  END T.
END M.
```
What are the fully qualified names of the roles used by AttB2 and AttB3?
Thanks, Stefan

**Comment by claeis** [comment]
The Interlis 1 model is internally translated to an Interlis 2 model.

Normally, one role name is the name of the reference attribute, and the other is the table name, that contains the reference attribute. And the association name is the concatenation of the two. (if this results not in a name conflict). AttrB2 in the example is like:

```
    ASSOCIATION BAttrB2 =
      B -- {0..*} B;
      AttrB2 -- {1} A;
    END BAttrB2;
``` 
Thus, the qualified names are: ```M.T.BAttrB2.B``` and ```M.T.BAttrB2.AttrB2```.

If there is a name conflict (as is the case with AttrB3 in the example), the name is extended with a index starting at 2. So AttrB3 results in:

```
    ASSOCIATION B2AttrB3 =
      B2 -- {0..*} B;
      AttrB3 -- {1} A;
    END B2AttrB3;
``` 
Thus, the qualified names are: ```M.T.B2AttrB3.B2``` and ```M.T.B2AttrB3.AttrB3```.

The qualified role names are shown in the log (if you are unsure).

**Comment by beistehen** [comment]
Thanks for this background information, Claude. I am aware of the entries in the log file but I was not sure about the rule that applies when name conflicts occur.
Does the indexing start in a sequential manner (from the top of the model) or is it random?

**Comment by claeis** [comment]
The index starts for role names per table and for the association per topic.
