### ISSUE TITLE
ilivalidator stops validation before the end of ITF file

### ISSUE THREAD

**Issue by zeeami123** [claeis/ilivalidator#160]
When trying to validate the file 242FME_CH.itf with ilivalidator 1.9.3, it stops before the end of the file with the following error message :
Error: failed to build polygons
Info: ...validation failed

I don't understand why this happens when looking at the data.
Do you have an explanation ?
[242_XTF_check.zip](https://github.com/claeis/ilivalidator/files/2603156/242_XTF_check.zip)

**Comment by beistehen** [comment]
In line 51 of the log file, the first error is recognised. It states that something is wrong with the geometry of object having tid 1341. Looking at object 1341 in the itf it reveals the following:

```
OBJE 1341 97843327
STPT 2509787.768 1142594.162
ARCP 2509783.531 1142596.407
LIPT 2509778.999 1142594.844
ARCP 2509783.531 1142596.407
LIPT 2509787.768 1142594.162
ELIN
```

So basically you have 5 points that should form a polygon. But in the excerpt above one can identify that some points have the same coodinates. That means that the polygon is built in the manner `A - B - C - B - A` which is not a true polygon. This is recognised by ilivalidator.

**Comment by zeeami123** [comment]
Thank you for your rapid answer, but my question still is : did ilivalidator check the whole ITF file ou did it stop at the object describred as  Info: 242FME_CH.itf: MD01MOCH24MN95F.Zones_glissement BID=itf16 ?
It's not clearly indicated at the end of the log file.

**Comment by beistehen** [comment]
I see. You are right, it is hard to tell.
Usually, the statistics are at the end of the log file, when the two validation passes have been run through. As in your data the TOPIC Zones_glissement is empty, there are probably no statistics written for this topic. But in my opinion this shoud be indicated with a log message like "0 objects in CLASS xy" or "empty TOPIC" or something similar.

Also, according to the log file, a second validation pass has not been run, which is unusal for a complete validation.
@claeis can you shed some light on the validation cycles here?

In the meantime: try to disable polygon building with the `--skipPolygonBuilding` switch, so you should get a "validation done" message at the end of the log file. Then, I guess, the whole itf has been checked.
