### ISSUE TITLE
Double low-9 quotation mark not found

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#161]
As far as I understand double low-9 quotation marks are not allowed (Annex B Referenzhandbuch):

`<OffiziellerTitel>Niederbuchsiten: Teilzonen- und Erschliessungsplan „Unterdorf“ mit Zonenvorschriften</OffiziellerTitel>`

ilivalidator-1.9.3 does not find them.

**Comment by beistehen** [comment]
When I read this excerpt of the RefHB (Chapter 3.3.2) ...

> Kommen im Transfer Zeichen vor, die nicht im beim Modell definierten Zeichensatz (vgl. Kapitel 2.5 Modelle, Themen, Klassen) vorkommen (oder gemäss Anhang D, wenn die Angabe des Zeichensatzes beim Modell fehlt), ist es der Software überlassen, wie sie damit umgeht (z.B. stillschweigend ignorieren oder mit Hinweis durch ein Ersatzzeichen ersetzen).

... ilivalidator does not have to care about any character because everthing is allowed.
But it would definitely be nice to get a hint from ilivalidator about the data being out of scope of Annex D (Zeichentabelle).
