### ISSUE TITLE
Missing tag BINBLBOX for BlackboxTypes

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#165]
Gemäss ÖREB-Rahmenmodell werden die Legendensymbole mittels Blackboxes codiert. Wenn das Tag BINBLBOX fehlt, muss der ilivalidator reklamieren.
Beispiel falsch:
<SYMBOL>iVBORw0KGgoAAAANSUhEUgAAAJ...</SYMBOL>
Beispiel korrekt:
<SYMBOL>
  <BINBLBOX>iVBORw0KGgoAAAANSUhEUgAAAJ...</BINBLBOX>
</SYMBOL>

**Comment by claeis** [comment]
fixed in c3b99887c693ae449ff85d0af94ecb6f736efa59
