### ISSUE TITLE
iliValidator stoppt bei Constraintüberprüfung

### ISSUE THREAD

**Issue by mwildi** [claeis/ilivalidator#173]
Beim Prüfen von ILI1-Files der AV bleibt der iliValidator (Version 1.9.3) bei der Prüfung des Constraints bei der Klasse Einzelobjekte.EONachfuehrung stehen. Die Abschlussmeldung erscheint nicht.
Beim Import auf der AI werden diese fehlerhaften Files trotz Parameter "force" nicht übersprungen. Der Importprozess bleibt hängen.

[DM01AVCH24LV95.zip](https://github.com/claeis/ilivalidator/files/2675358/DM01AVCH24LV95.zip)

**Comment by claeis** [comment]
https://github.com/claeis/iox-ili/commit/50522bd51f00b38bc7bc99520308c3c6090297b7
