### ISSUE TITLE
Xtflog contains not all messages

### ISSUE THREAD

**Issue by stflustop** [claeis/ilivalidator#187]
If a model could not be found, you will find in the Log-File a message like:
Error: GeometryCHLV95_V99: model not found
This message is part of the Xtflog

[Testdata.zip](https://github.com/claeis/ilivalidator/files/2900086/Testdata.zip)

**Comment by beistehen** [comment]
You mean

"This message is _not_ part of the Xtflog"

(but it should be)?

**Comment by stflustop** [comment]
Yes
