### ISSUE TITLE
heap space

### ISSUE THREAD

**Issue by Rensolid** [claeis/ilivalidator#190]
Hello 

Im using the Ilivalidator 1.10.0 and after 5min running it says "Error: Java heap space"
Also it says in the beginning: "Info: maxMemory 253440 KB"
I saw someone already mentioned this issue and solved it with "Xms1024m". I added this to the Java Runtime Paramters, but didnt have any influence on that maxMemory.

I would prefer not to edit the java files, is there any way to solve this issue?

Thanks in advance

![grafik](https://user-images.githubusercontent.com/48287101/53937973-02169680-40af-11e9-831f-1aee1e7d01f7.png)

**Comment by beistehen** [comment]
For Windows I use a batch script to run ilivalidator. It looks like this:

```
"C:\Program Files\Java\jdk1.8.0_131\bin\javaw.exe" -Xmx7000m -jar "<path-to-ilivalidator-1.10.0.jar>"
pause  
```

Please note:
-Xm_s_ sets the initial memory where as -Xm_x_ sets the maximum memory allowed.

**Comment by edigonzales** [comment]
Any chance to provide the transfer file? Is it a large one? Lots of relations etc?

Not sure how it works on Windows and/or in the GUI. This works on cli on macOS/Linux:

`java -Xmx64m -jar /Users/stefan/apps/ilivalidator-1.10.0/ilivalidator-1.10.0.jar Downloads/ch_254900/ch_254900.itf`

**Comment by Rensolid** [comment]
great, thx for the help!

`java -Xms1500m -jar "D:\XXX\ilivalidator-1.10.0\ilivalidator-1.10.0.jar"
pause`

worked for me. had to make sure its all located on my local harddrive.

THX!

**Comment by claeis** [comment]
see the java docs for java options, for example [here](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html)

1GB heapspace works for most use cases fine.
