### ISSUE TITLE
XMLDate has to be checked stronger (YYYY-MM-DD)

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#197]
Gemäss XML-Spezifikation muss ein XML-Datum mit YYYY-MM-DD angegeben werden und nicht YYYY-M-D. In den einleitenden Abschnitten zu den Kap. 3.1 und 3.3 im INTERLIS Referenzhandbuch stützt man sich bei der Codierung für den Transfer auf diese XML-Spezifikation. Der ilivalidator sollte somit bei einem in der Form YYYY-M-D codierten Datum reklamieren.

**Comment by patrickackermann** [comment]
@claeis, Ich arbeite an diesem Issue.
