### ISSUE TITLE
enable URLs as valid path to a source file

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#199]
When validating data while using an external catalog file it would be useful to point to the URL (usually in a model repository) where the catalog file can be downloaded (and stored in the cache?).

E.g.
`java -jar ilivalidator.jar path/to/localdata.xtf https://models.geo.admin.ch/ARE/Hauptnutzung_CH_V1_1.xml`

**Comment by claeis** [comment]
see also #290
