### ISSUE TITLE
Missing test classes

### ISSUE THREAD

**Issue by leader80** [claeis/ilivalidator#2]
Hi Claeis,

best practice in java are to provide the testclasses to check the quality and the stability of the program, it is also practical to explain how to use the code and how to inplement it. 
I suggest to start slowly to build them, I would like also to help you but I need more code information.

Best regards
G.

**Comment by claeis** [comment]
The main validation happens in project iox-ili. So most developer level tests should be there.
And I hope to see a project that develops a test suite from a user point of view, that is validator/checker independent.

**Comment by claeis** [comment]
added some tests to validate general functionality and show usage
