### ISSUE TITLE
Messages in logfile are unordererd

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#20]
Messages (Errors and Warnings) should be orderered by TID or the line number of the object in the logfile.

**Comment by claeis** [comment]
Not sure if this is a good idea, because it is an additional source/risk of bugs and some runtime effort.

And, in some use cases (validation on export, validation on db), there is no line number and/or the TID is not yet visible to the user.

**Comment by edigonzales** [comment]
I think it's only annoying when having tons of errors and using the pure log file. In this case *I* would use the xtf log file and convert it to GeoPackage for having sortable attributes.
