### ISSUE TITLE
How to disable OID validation in toml file?

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#200]
What is the best way to disable OID validation in a toml file? I want to suppress error messages like ``Error: line 4026: SIA405_WASSER_2015.SIA405_Wasser.Rohrleitungsteil: tid 5508609C-2420-468E-9069-F3B04D8099C3: value <5508609C-2420-468E-9069-F3B04D8099C3> is not a valid OID
``

Thanks,
Stefan

**Comment by claeis** [comment]
There is no setting to disable the ID validation.
