### ISSUE TITLE
Error: polygons overlay

### ISSUE THREAD

**Issue by KTAI-GIS** [claeis/ilivalidator#202]
[Erschliessungsstand_AI_20190617.zip](https://github.com/claeis/ilivalidator/files/3297112/Erschliessungsstand_AI_20190617.zip)
We get some "polygon overlay" Errors for AREA datatype whis correct Interlis2 XTF Files. Some checks with Interlisstudio and IGCheck were successful. However the ilivalidator 1.9.3 and 1.11.0 is reporting polygon overlays. Moreover the ili2db V3.12.2 and V4.1.0 cannot handle the topology as well. Data files for a testcase are attached. We really stuck with this issue.

I wrote a new issue because this one was already closed #123

**Comment by beistehen** [comment]
Please see my comment [here](https://github.com/claeis/ilivalidator/issues/123#issuecomment-411376728) and the following discussion.
Regards,
Stefan

**Comment by KTAI-GIS** [comment]
Hi Stefan
Thanks for the hint. After reading your Posts I did some more Tests.
I tried to generate the Polygons from the centroids and edges with rounded coordinates but with no success.
Best regards, Pascal

**Comment by KTAI-GIS** [comment]
Some new and reduced test data
[es_testdaten_20190625.zip](https://github.com/claeis/ilivalidator/files/3819788/es_testdaten_20190625.zip)
