### ISSUE TITLE
objectCount(Role) meldet keinen Fehler

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#203]
Der Test

```
		CONSTRAINTS OF ClassS =
			MANDATORY CONSTRAINT
		   		(INTERLIS.objectCount(t1)) == 2;
		END;
```
meldet keinen keinen Fehler, falls die Anzahl der Rollen, welche von S zu T referenzieren, 0 ist. Es funktioniert bei 1.

**Comment by claeis** [comment]
Value ist in diesem Fall undefinied und skipped die Evaluierung. 

https://github.com/claeis/iox-ili/blob/bf812ae556abce4cbc16f0f6e92d7a626829954f/src/main/java/ch/interlis/iox_j/validator/functions/Interlis.java#L136
