### ISSUE TITLE
Error: must not have an OID

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ilivalidator#207]
Again I have a OID issue, which only occures since version 1.11.1 (no errors in 1.11.0). This is the error message: 

> Error: line 19: Waldabstandslinien_LV95_V1_1.Geobasisdaten.Typ_Dokument: tid 100007: Association Waldabstandslinien_LV95_V1_1.Geobasisdaten.Typ_Dokument must not have an OID (100007)

> 

I could not find any sign in the Changelog for a new check. What can that be? Any suggestions?
I have attached the xtf and the log in the zip-file.
[Waldabstandslinien.zip](https://github.com/claeis/ilivalidator/files/3711218/Waldabstandslinien.zip)

**Comment by edigonzales** [comment]
I think it's this one: https://github.com/claeis/ilivalidator/issues/201

**Comment by kuhnpa** [comment]
The issue is solved when I use the ili2gpkg 4.3.0 instead of 3.12.2

**Comment by kuhnpa** [comment]
I don't really understand why this issue occures. When I create the schema with ili2gpkg the table created "geobasisdaten_typ_dokument" has the mandatory primary key "T_Id" which, when using the export function of ili2gpkg, is written as "superfluos OID". From my pont of view ili2gpkg should delete this OID during the export, in order create a clean XTF.

**Comment by claeis** [comment]
It is not related to the t_id in the (ili2db generated) DB.
ili2db<4.2.0 exported a superfluous TID in standalone assocs (claeis/ili2db#292).
ilivalidator<1.11.1 didn't report such superfluous TIDs (#201). 
Unfortunately, both issues have not been listed in the changelogs. Sorry for that.
