### ISSUE TITLE
1.11.1: GC overhead limit exceeded

### ISSUE THREAD

**Issue by dkottmann** [claeis/ilivalidator#208]
with ilivalidator 1.11.1: 
`java -Xmx1024m -jar #{ILIVALIDATOR_PATH} --modeldir '#{ili_models_dir};http://models.interlis.ch/' --log #{validator_log_path} --xtflog #{validator_xtf_log_path} #{File.basename(filepath)}  --forceTypeValidation --allowItfAreaHoles`

Logfile: https://geodienste.ch/validation/104

ERROR: GC overhead limit exceeded

Data: https://geodienste.ch/downloads/interlis/av/BS/av_BS_lv95.zip 

Error cannot be reproduced with ilivalidator 1.9.3 for same itf: 
https://geodienste.ch/data_agg/import_tasks/9554/logs

**Comment by beistehen** [comment]
Have you tried running it with more memory, like `-Xmx4096m` instead of `-Xmx1024m`?

**Comment by dkottmann** [comment]
@beistehen 

> Have you tried running it with more memory, like -Xmx4096m instead of -Xmx1024m?

No. We could try that, but I actually prefer a solution in ilivalidator since previous versions worked with our -Xmx setting. 

Ilivalidator has been optimised before in #8 

Dou you know which changes in ilivalidator since Version 1.9.3 might cause this issue?

**Comment by beistehen** [comment]
No, I don't know what changes might cause this additional memory consumption. But I guess that every additional check (and the changelog of v1.10.0 lists many of them) might require additional resources (memory- and cpu-wise).

@claeis Is there a rule of thumb for what the best setting for `-Xmx` is? Or a correlation between `-Xmx` and the .itf/.xtf file size or number of (geometric) objects?

**Comment by claeis** [comment]
I would not use -Xmx, except in a server environment.

**Comment by claeis** [comment]
@beistehen No, there is no rule of thumb. It depends on the number of curve segments per attribute, but also on the position and noding of these segments.

**Comment by claeis** [comment]
Analyzed and no new (wrong) memory consumption found.
