### ISSUE TITLE
Open JDK and ilivalidator - question

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#210]
Due to the new licence strategy of Oracle it can happen that users will remove the "Standard Java Runtime" from their PC and will use Open JDK.

Is there anything to consider when using ilivalidator? Is it tested and OK right now? (I believe there should be no difference  ...))

**Comment by edigonzales** [comment]
I'm using AdoptJDK https://adoptopenjdk.net/ which are prebuilt OpenJDK binaries without any problems.

**Comment by claeis** [comment]
I'm not aware of issues. I'm using https://github.com/ojdkbuild/ojdkbuild

**Comment by Pierre-de-la-Verre** [comment]
Thanks to both. Solved for me.
