### ISSUE TITLE
CONSTRAINTs: Questions

### ISSUE THREAD

**Issue by pramisters** [claeis/ilivalidator#212]
We have extended a MGDM of the federation and need to further constrain the permitted objects, at least at time of XTF-data-validation with ilivalidator.

Is it possible to define the following constraints (generally and specifically in an extended model), so that ilivalidator finds violations of them?
And if yes, what would the constraint look like in the INTERLIS model (or in a TOML-File for the ilivalidator)?

1. To limit SURFACE objects to a certain square measure, e.g. 10: Is there a function to calculate the numerical area value (of SURFACE or AREA objects) that can be used in a CONSTRAINT?

2. According to the "Referenzhandbuch" (2.8.13.4) further constrain a SURFACE definition (in the MGDM) to an AREA definition (in the extended model) is permitted. How does the INTERLIS code look like?

3. How can SURFACE objects be constrained, so that holes ("doughnut") are not permitted (nur 1-fach zusammenhängende Fläche erlaubt)?

**Comment by edigonzales** [comment]
2. `https://github.com/claeis/iox-ili/blob/1e52debc219746dc4fba95ee4cb3a21c5924096e/src/test/data/validator/SetConstraint23.ili#L30`

**Comment by edigonzales** [comment]
1. Not that I'm aware of. But it would be a simple plugin written in Java: https://github.com/claeis/ilivalidator/blob/master/demoplugin/src/org/interlis2/validator/demo/CheckGebaeudeVersicherungsSystemIoxPlugin.java
3. dito

**Comment by pramisters** [comment]
Danke Stefan für den wertvollen Input!
