### ISSUE TITLE
Write coordinates to log-file?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#218]
Is it already (optional?) possible to write the coordinates (of point elements) to the log-file? It would be helpful to find the elements in the graphic interface ..

**Comment by claeis** [comment]
the coordinates appear in the ``--xtflog file.xtf``. For objects with line or polygon geometries, it is the coordinate of the first vertex.

**Comment by Pierre-de-la-Verre** [comment]
Thanks, I see
