### ISSUE TITLE
AREA validation: duplicate objects are not detected

### ISSUE THREAD

**Issue by dkottmann** [claeis/ilivalidator#219]
"grundnutzung" (AREA type) includes large duplicate areas, which Ilivalidator-1.11.3 does not complain about.

Data (contains ilivalidator Logfile, XTF and additional KML-File : 
[Muotathal.zip](https://github.com/claeis/ilivalidator/files/4086668/Muotathal.zip)

--> object with xtf_id 21814 overlaps objects with xtf_id 22457, 23699, 21719, 21714 etc.

Issue is visualized here (the KML file is also in the ZIP above)
https://s.geo.admin.ch/86ee83ffcb

**Comment by claeis** [comment]
fixed with #263
