### ISSUE TITLE
Documentation: please check it

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#220]
The doc (readme.txt, RST) for the program seem to be in some parts not up-to-date.
- INI versus TOML
- Java is no more free in every case
- What to do with memory problems
- maybe more details

It would be great for simple users to see updated info.
Thanks!

**Comment by claeis** [comment]
- ...and "interne Id des Constraints"

**Comment by claeis** [comment]
- explain log

**Comment by Philippluca** [comment]
@claeis Ich sehe hier nur im Bereich INI / TOML noch Handlungsbedarf. JRE ist ja weiterhin gratis und der Rest wurde bereits erweitert. Siehst du das auch so?

Die Entwicklerdoc werde ich um die Python & rst2html Abhängigkeit erweitern.

**Comment by claeis** [comment]
Ja.
- INI/TOML ist mehr ein Typo; "INI" ist richtig ("TOML" ist veraltete Dok)
- JRE (evtl. Hinweis das jede OpenJDK basierte JRE Dist funktioniert)
