### ISSUE TITLE
Command line: use options without a data-file

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#223]
The syntax is defined in this way:
`java -jar ilivalidator.jar [Options] [file]`

For empty GUI it is:
`java -jar ilivalidator.jar`

But how to call a GUI with settings (log-file, ini-file, ..), but without data file?
When I try "java -jar ilivalidator.jar [Options]" I always get the error 

> Info: ilivalidator: wrong number of arguments; ignored

**Comment by beistehen** [comment]
Running the GUI with options is not implemented at this time. What would be your use case?
Regards, Stefan

**Comment by Pierre-de-la-Verre** [comment]
It would be more comfortable - to start a program with a defined configuration (with a "profile") is common state of the art.

**Comment by claeis** [comment]
use ```--gui```

**Comment by Pierre-de-la-Verre** [comment]
But it seems that "--gui" can not be combined with a part of options:

`D:\Program Files\ilivalidator>java -jar "d:\Program Files\ilivalidator\ilivalidator.jar"  --gui --log result.log
Info: ilivalidator: wrong number of arguments; ignored
Exception in thread "main" java.lang.NullPointerException
        at org.interlis2.validator.gui.MainFrame.setXtfFile(MainFrame.java:432)
        at org.interlis2.validator.gui.MainFrame.main(MainFrame.java:559)
        at org.interlis2.validator.Main.main(Main.java:168)
`

**Comment by beistehen** [comment]
As I saw in the code there are some issues using `--gui` at this time. That might be the reason why this option is not documented yet.
But I agree that working with "profiles" would be helpful.

**Comment by claeis** [comment]
I don't like the mixed mode, but it should work now.

**Comment by Pierre-de-la-Verre** [comment]
Please modfiy the documentation, e.g. in RST files and in main-page, where I find:

java -jar ilivalidator.jar [options] file.xtf

**Comment by claeis** [comment]
Should I add a link to https://de.wikipedia.org/wiki/Kommandozeile
Or what exactly is unclear/missing?

**Comment by Pierre-de-la-Verre** [comment]
Sorry, my bad. I'm always fixed to the GUI-usage and thought that the line which I mentioned above should be display the XTF-file also as [optional]. But that's wrong...   :-((

Have a good time!
