### ISSUE TITLE
Deactivate "nachHaltungspunktRef should associate 1 to 1 target objects (instead of 0)"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#226]
I have tons of errors like 
"   ... nachHaltungspunktRef should associate 1 to 1 target objects (instead of 0)"

Is it possible to disable this part of the validation?

**Comment by beistehen** [comment]
Yes, it is possible.

Create a config file (aka `.toml` file) with the following content:
```
["<insert.qualified.path.to.role.here>"]
multiplicity="off"
```

So in your case presumably:
```
["SIA405_ABWASSER_2015.SIA405_Abwasser.Haltung_nachHaltungspunktAssoc.nachHaltungspunktRef"]
multiplicity="off"
```

Then add the config file to your check (in the GUI or via command line options). The errors should disappear in the logfile.

**Comment by Pierre-de-la-Verre** [comment]
Thanks for advice. I see, without the a look at the reference manual it is not that easy for a simple standard user ..

**Comment by Pierre-de-la-Verre** [comment]
Sorry, me again ..

Is it also possible to deactivate the check "No object found with OID .... in basket .."?

**Comment by claeis** [comment]
No, not in general, only per Role/Reference (as already mentioned). 

If the RolDef is EXTERNAL (only then!), the option ```--allObjectsAccessible``` can help.
