### ISSUE TITLE
partially Extended ILI creates error: "Duplicate EnumElement name"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#227]
due to the rigid licence conditions I don't post the original ILI here, but I think it is understandable with this fictional example too
***
Example:

```
base.ili
status = (
    red,
    green,
    blue,
    yellow
)

myspecial.ili
status EXTENDS status.base.ili =(
    red (
        light red,
        dark red),
    green,
    blue (
        light blue,
        dark blue),
    yellow
)
```

So - red and blue are extended, green and yellow not.

Ilivalidator stops with
```
Error: myspecial.ili:97:Duplicate EnumElement name "green".
Error: compiler failed
```
When I delete the line with "green", then I get the same problem with "yellow".
Is the "not expanded green" a problem of the ILI or a probem of ilivalidator?

**Comment by claeis** [comment]
A problem of the ILI. You can not repeat a value (except you extend it; red and blue in your example).

**Comment by Pierre-de-la-Verre** [comment]
OK, thanks.
But maybe the software could accept this kind of wrong definitions, as long as nothing "really wrong" happens? (But maybe my simple-user-view is a little bit naive ..)

**Comment by claeis** [comment]
No, I think effort should go into correct models and correct data, and not into software that accepts incorrect model/data.
