### ISSUE TITLE
Missing check when write to "unwriteable" log-file

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#228]
2nd priority, but could happen ..

When the user defines a log-file which cannot be created (write protection; no access right), the ilivalidator just ignores this problem and starts the check without a message - and without a log-file.

Suggestion:
Add a "is the log file really created - check" and inform the user:
`c:\no_rights\locked\already_opened.log can not be created. Please select another path / name.`

**Comment by claeis** [comment]
Can not reproduce. I see a proper error message on the console:

   ```log\ce.txt (Access is denied)```

**Comment by Pierre-de-la-Verre** [comment]
I use the GUI, with new version 1.11.4. 
When I select the file with the "file dialog", then I get an alert "Unwriteable". But when I just enter the filename into the dialogue, then it behaves as described.
