### ISSUE TITLE
Validation stalls

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#23]
Validation stalls with some ITF.

`Info: removeOverlap(): valoverlap Intersection overlap 8.053476221714373E-4, coord1 (2668564.7084629317, 1207138.2917020593, NaN), tid1 19251, tid2 19274, idx1 4, idx2 6, seg1 CIRCULARSTRING (2668562.898 1207137.754, 2668563.929 1207137.79, 2668564.78 1207138.374), seg2 (2668564.308 1207137.831, 2668564.78 1207138.374) (PolygonizeGraph.java:271)`
`Info: buildSurfaces(): georef polygons..._itf_geom_BoFlaeche (ItfAreaLinetable2Polygon.java:283)`
`Info: read(): GebaeudenummerPos... (ItfReader.java:203)`
`Info: read(): Objektname... (ItfReader.java:203)`
`Info: read(): ObjektnamePos... (ItfReader.java:203)`
`Info: read(): BoFlaecheSymbol... (ItfReader.java:203)`
`Info: read(): Einzelpunkt... (ItfReader.java:203)`

ITF sent by email to claeis.

**Comment by edigonzales** [comment]
This is most probably due to size of the ITF. Attached ITF is still running after 20 minutes.

[258100.itf.zip](https://github.com/claeis/ilivalidator/files/677101/258100.itf.zip)

**Comment by edigonzales** [comment]
258100.itf took 29 minutes to validate.

**Comment by claeis** [comment]
see #18

**Comment by renato1987** [comment]
This issue is solved with release 0.9.0.
