### ISSUE TITLE
GUI should support Drag and Drop

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#230]
Für Nutzer/innen des GUI: Statt die zu prüfenden Daten manuell einbinden zu müssen, sollten sie mit Drag and Drop in den ilivalidator gezogen werden können, unabhängig von der Anzahl gleichzeitig zu prüfenden Dateien (z.B. Sachplandaten mit den zwei dazugehörenden Katalogen).

**Comment by patrickackermann** [comment]
@claeis, Ich arbeite an diesem Issue.
