### ISSUE TITLE
Wish: "Job done" message in GUI

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#234]
Just a small wish from a GUI user:
Please add a message (and a beep??) to the GUI when the validation is finished. At the moment it is not easy to see if the job is done or not.

Thanks

**Comment by claeis** [comment]
A message is already there:
   
     Info: ...validation done

Or, do you expect a message box?

**Comment by Pierre-de-la-Verre** [comment]
This message is at the end of the displayed data and can not be seen without searching and scrolling (very often again and again ..). So a message box or a text in the dialogue would be a fine solution.

A "status bar" with text or symbols for "running / done / waiting / crashed ..." could be the next step, but is not first priority ...

**Comment by beistehen** [comment]
What about a quick fix: scrolling in log window is automatically adjusted so that the last line at the bottom is always visible?

**Comment by Pierre-de-la-Verre** [comment]
I'm not a coder, but AFAIK a dynamic scrolling (especially with the really long lists) needs a lot of resources.
But a final "when job is done then jump to last line" shows two information:
- job is done
- user sees the (main) results
