### ISSUE TITLE
fails to lookup ili24 model if xtf24 transfer file

### ISSUE THREAD

**Issue by claeis** [claeis/ilivalidator#239]

**Comment by claeis** [comment]
Das Problem kann auch bei 2.3 Daten dazu führen, dass das Modell nicht gefunden wird.

    Info: lookup model <CoordSys> in repository <http://models.interlis.ch/>
    Info: lookup model <Units> 2.4 in repository <http://models.interlis.ch/>

Weil das Programm nach 2.4 statt 2.3 Versionen der Modelle sucht. Und die gibt es evtl nicht. Darum die Fehlermeldung, dass das Modell nicht gefunden wird.

Und es sucht nach 2.4 Versionen, weil das erste Modell (CoordSys) das es findet, eine 2.4 Version ist.

**Comment by dkottmann** [comment]
@claeis 

> Das Problem kann auch bei 2.3 Daten dazu führen, dass das Modell nicht gefunden wird.

Die Validierung (und somit der Import) von Daten gemäss MGDM Wildruhezonen (MODEL `Wildruhezonen_LV95_V2_1`) funktioniert auf geodienste.ch nicht mehr seit den Anpassungen auf http://models.interlis.ch bezüglich INTERLIS 2.4. 
Am 23.4.2020 hatte es mit ilivalidator 1.11.5 z.B. noch funktioniert. 

Fragen: 

- Sind potentiell weitere MGDM betroffen? Welche bzw. lässt sich das (ohne Tests) einfach herausfinden? 
- Ist der Fehler auch bei ilivalidator < 1.11.5 zu erwarten? 
- Könnte der Patch rückwirkend in fürheren, betroffenen Versionen (z.B: 1.11.5) bereitgestellt werden? 
- Oder gibt es einen einfachen Workaround, damit die Validierung mit ilivalidator <= 1.11.5 weiterhin funktoniert? Kopie der betroffenen Modelle in den lokal verwendeten ili-Ordner?

**Comment by claeis** [comment]
- Das Problem hat nichts mit dem MDM zu tun.
- Der Fehler ist nur bei ilivalidator 1.11.5 zu erwarten (>ili2c-5.0.7 UND <ilivalidator-1.11.6).
