### ISSUE TITLE
SURFACE WITH (STRAIGHTS) als MULTISURFACE(CURVEPOLYGON in PostGIS

### ISSUE THREAD

**Issue by romefi** [claeis/ilivalidator#245]
Wir haben das Modell [KbS_LV95_V1_4 ](http://models.geo.admin.ch/BAFU/KbS_V1_4.ili) mit den [Daten](https://www.geodienste.ch/downloads/interlis/kataster_belasteter_standorte/SH/kataster_belasteter_standorte_v1_4_SH_lv95.zip) und diesem [TOML](https://github.com/claeis/ilivalidator/files/4473957/KbS_LV95_V1_4.zip) importiert.

Obwohl die Flächengeometrie im Modell ` Polygon = SURFACE WITH (STRAIGHTS) VERTEX GeometryCHLV95_V1.Coord2 WITHOUT OVERLAPS > 0.001;` definiert ist, werden die Daten als `MULTISURFACE(CURVEPOLYGON(COMPOUNDCURVE(` in PostGIS abgelegt. Erst mit der Option `--strokeArcs` werden die Flächen in PostGIS als `MULTIPOLYGON(((` abgelegt. 

Wieso wird der Geometrietyp `MULTISURFACE(CURVEPOLYGON` in PostGIS abgelegt, obwohl das Modell ARCS nicht zulässt?

**Comment by claeis** [comment]
Das ist das falsche Repos für ili2db Anliegen.

ili2pg verwendet aktuell nicht das Modell um zwischen Polygon und CurvePolygon (LineString und CompoundCurve) zu unterscheiden. Polygon und LineString kann aktuell nur mittels --strokeArcs erzwungen werden.

Siehe neue Funktion claeis/ili2db#34
