### ISSUE TITLE
Check Base64 input character

### ISSUE THREAD

**Issue by mizehn** [claeis/ilivalidator#246]
Beim ili2pg-Import (v4.4.2) gibt es nach erfolgreicher ilivalidator v1.11.5 Prüfung folgenden Fehler:
Logfile: [PZ.log](https://github.com/claeis/ilivalidator/files/4480729/PZ.log)
Error: Object ZPR at (line 5,col 65)
Error:   java.io.IOException: Bad Base64 input character decimal 58 in array position 4
Error:     Bad Base64 input character decimal 58 in array position 4
Error: Object A at (line 6,col 63)
Error:   java.io.IOException: Bad Base64 input character decimal 58 in array position 4
Error:     Bad Base64 input character decimal 58 in array position 4

Müsste der Fehler nicht bereits im ilivalidator erkannt werden?

Vmtl. fehlerhafte BLACKBOX BINARY-Codierung?
<Planungszonen_LV95_V1.Geobasisdaten.Typ_Planungszone TID="ZPR"><Code>ZPR</Code><Bezeichnung>Zonenplanrevision 2. Ratschlag</Bezeichnung><Festlegung_Stufe>Gemeinde</Festlegung_Stufe><Bemerkungen>Planungszone Zonenplanrevision</Bemerkungen><Symbol><BINBLBOX>http://mapserver.geo.dev.bs.ch?version=1.3.0&amp;SERVICE=WMS&amp;SLD_VERSION=1.1.0&amp;FORMAT=image/png&amp;STYLE=default&amp;REQUEST=GetLegendGraphic&amp;LAYER=OEREB_PZ_Planungszonen=</BINBLBOX></Symbol></Planungszonen_LV95_V1.Geobasisdaten.Typ_Planungszone>

Daten: [PZ_Planungszonen_LV95_V1.zip](https://github.com/claeis/ilivalidator/files/4480744/PZ_Planungszonen_LV95_V1.zip)

Modell: https://models.geo.admin.ch/ARE/Planungszonen_V1.ili

**Comment by claeis** [comment]
Ja, der Fehler müsste bereits im ilivalidator gemeldet werden.
