### ISSUE TITLE
itf: check default file encoding, must be ISO-8859-1

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#251]
... or update documentation and state, that no check of encoding is done because too error-prone and unreliable?

**Comment by beistehen** [comment]
TIL that for `itf` not the whole character set of ISO 8859-1 is allowed in TextType values but only a subset (see RefHB chapter 3.4.5.5) 😕
So what about using a regexp to check TextType values [here](https://github.com/claeis/iox-ili/blob/af96d067713136f5ecbe0945a2132cf7127f07b8/src/main/java/ch/interlis/iox_j/validator/Validator.java#L3736)? This could be done independently of the encoding of the file.

**Comment by claeis** [comment]
an encoding can not be validated (except for bytes undefined by the encoding or except you know the content), because it is an interpretation of the bytes.

**Comment by beistehen** [comment]
I agree. Hence my suggestion to state in the documentation that encoding in general is not validated for `itf`.

But assuming ISO 8859-1 encoding in the `itf` there could be a byte-wise check of TextType values which would log a warning (or error) if a byte code shows up that is not allowed according to RefHB 3.4.5.5.?

**Comment by claeis** [comment]
create a new issue, if needed (i assume a lot of files/tranfers would fail...)
