### ISSUE TITLE
Cosmetic(?) inconsistence(?): modeldir versus ilidir

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#256]
The batch command request a --modeldir, the GUI shows "Modellverzeichnisse".

But:
The file .ilivalidator stores "ilidirs", the log-files report also "ilidirs".

What's the reason behind this?

**Comment by claeis** [comment]
In the code it is called ilidirs. And in ili2c the command line option is called ```--ilidirs```
