### ISSUE TITLE
Problem: Empty "Perimeter / Surface" hangs the programm

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#258]
As result from #255 I found this:

`<?xml version="1.0" encoding="utf-8"?>
<TRANSFER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.interlis.ch/INTERLIS2.3" xmlns="http://www.interlis.ch/INTERLIS2.3">
  <HEADERSECTION VERSION="2.3" SENDER="AG">
    <MODELS>
      <MODEL NAME="TG12_01_DSS_2015_WI_LV95" VERSION="2017-05-10" URI="http://www.giv.tg.ch" />
    </MODELS>
  </HEADERSECTION>
  <DATASECTION>
    <TG12_01_DSS_2015_WI_LV95.Siedlungsentwaesserung BID="ch123ab456780006">
      <DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet TID="ch123ab456783127">
        <Metaattribute>
          <SIA405_Base_LV95.Metaattribute />
        </Metaattribute>
        <Abflussbeiwert_SW_Ist>0.30</Abflussbeiwert_SW_Ist>
        <Bemerkung>Regenabwasser</Bemerkung>
        <Bezeichnung>M26.1-M27.10</Bezeichnung>
        <Einwohnerdichte_Ist>0</Einwohnerdichte_Ist>
        <Entwaesserungssystem_Ist>Trennsystem</Entwaesserungssystem_Ist>
        <Perimeter>
          <SURFACE />
        </Perimeter>
      </DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet>
    </TG12_01_DSS_2015_WI_LV95.Siedlungsentwaesserung>
  </DATASECTION>
</TRANSFER>`

The "Perimeter / Surface" brings the program to hangs (it runs endless with full load of CPU and increasing usage of RM - see image at #255 
When it is removed the program runs fine.

**Comment by edigonzales** [comment]
see https://github.com/claeis/ilivalidator/issues/216

**Comment by claeis** [comment]
see #322

**Comment by claeis** [comment]
fixed in c3b99887c693ae449ff85d0af94ecb6f736efa59
