### ISSUE TITLE
Wish: GUI - output to window optional

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#259]
As side effect from #255 
The writing to the window slows down the software very much. I would like to see a new option (maybe a new toggle button in the dialogue):

**When a log-file is defined, then the output to the window can be suppressed.**

**Comment by Pierre-de-la-Verre** [comment]
Dachte nicht, dass das schon eine Zeitlang her ist ...

Ich will das noch einmal auffrischen - ich glaube, das gibt mit kleinem Aufwand eine gute Wirkung.

**Comment by claeis** [comment]
Die Ausgabe von Fehlermeldungen wird nun (automatisch) gestoppt (wenn eine Log-Datei definiert ist). Die Ausgabe von Info Meldungen bleibt, damit man den Fortschritt sieht.

**Comment by beistehen** [comment]
> Ergebnis:
> 
>     * genauso wie in Version 1.13.1 wird die Log-Datei erstellt und das Fenster mit ERROR gefüllt

Kann ich bestätigen.

**Comment by Pierre-de-la-Verre** [comment]
Es scheint hier ein Synchronisationsproblem vorzuliegen
Ich öffne die GUI und die XTF und ...
- definiere a.log und validiere: volle Anzeige plus Datei a.log
- validiere nochmals: kurze Anzeige mit Hinweis auf a.log plus Datei a.log
- definiere b.log, lösche Logfenster, validiere: 
- kurze Anzeige mit Hinweis auf a.log plus Datei b.log
- definiere c.log, lösche Logfenster, validiere: 
- kurze Anzeige mit Hinweis auf b.log plus Datei c.log
- entferne Log-Definition, lösche Fenster, validiere: kurze Anzeige mit Hinweis auf c.log, aber c.log wurde nicht verändert bzw. in diesem Lauf gar nicht erzeugt
