### ISSUE TITLE
Overlaying AREA not detected

### ISSUE THREAD

**Issue by KunoEpper** [claeis/ilivalidator#263]
Although validation run without errors, there are overlaying AREAs in xtf.
xtf_id: 1500049, 1500200, 1500043

Why that?

Find xtf and log file attached.

[Test.zip](https://github.com/claeis/ilivalidator/files/4924969/Test.zip)

**Comment by edigonzales** [comment]
Soweit ich es verstehe: Die AREA-Prüfung testet letzten Endes zuerst ob zwei Polygone identisch sind (dann wärs ja bereits ein Fehler), falls nicht wird geprüft, ob sie sich überlappen:

https://github.com/claeis/iox-ili/blob/master/jtsext/src/main/java/ch/interlis/iom_j/itf/impl/jtsext/geom/CurvePolygon.java#L106

Und hier liegt glaub der Hund begraben. Die Methode `polygon1.overlaps(polygon2)` liefert `FALSE` zurück, falls Polygon2 komplett innerhalb von Polygon 1 liegt. Ist zwar GEOS (nicht direkt JTS) aber nachzulesen z.B. hier: http://postgis.net/docs/ST_Overlaps.html: "Returns TRUE if the Geometries "spatially overlap". By that we mean they intersect, but one does not completely contain another."

Wenn man aus https://github.com/claeis/iox-ili/blob/master/jtsext/src/main/java/ch/interlis/iom_j/itf/impl/jtsext/geom/CurvePolygon.java#L106 quick 'n' dirty sowas macht: `return e0.equals(e1) || e0.overlaps(e1) || e0.within(e1) || e1.within(e0);` werden Fehler gemeldet. 

Beiliegend gepatchte Version zum Ausprobieren:

[ilivalidator-1.11.6-kuno.zip](https://github.com/claeis/ilivalidator/files/4925504/ilivalidator-1.11.6-kuno.zip)

Anders rum: Wenn man z.B. beim Polygon `1500049` die Koordinate `2716279.504` zu `2716279.505` macht, wird bereits mit Original-Ilivalidator ein Fehler gefunden. Weil es so eben nicht mehr innerhalb des anderen Polygons ist.

**Comment by KunoEpper** [comment]
Vielen Dank für die rasche Analyse inkl. Code! Top!

Einverstanden: Eine "Überlappung" besteht nicht. Es ist eine (vollständige) "Überdeckung". Damit wäre bei AREAs eine neue Regel nötig: "must not be coverd by feature of same feature class". Das führt dann zu einer echten "Gebietseinteilung".

Ich war mir dessen nicht bewusst und werde diese Regel zwischenzeitlich über andere Werkzeuge prüfen. Gerne probiere ich dabei den Code von oben.

**Comment by edigonzales** [comment]
The Power of OpenSource!
