### ISSUE TITLE
Separate GUI (Swing) classes from Main class

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#265]
Damit die Anwendung mit GraalVM zu native images kompilierbar ist, dürfen keine Swing-Abhängigkeiten in der Main-Klasse vorhanden sein.

**Comment by claeis** [comment]
does not yet work as expected

**Comment by claeis** [comment]
Wenn man die Klasse org.interlis2.validator.gui.MainFrame aus dem ilivalidator.jar File entfernt, funktioniert es.
