### ISSUE TITLE
Batch-mode does not use settings from c:\Users\USERNAME\.ilivalidator?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#269]
I thought that the batch-mode uses as default the modeldirs from "c:\Users\USERNAME\.ilivalidator" (just like the GUI does), and the parameter "--modeldir" is optional to define special paths to models.

But without "--modeldir" is uses only "Info: ilidirs <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels>"

So is it a bug or feature?

**Comment by claeis** [comment]
The cmdline only uses the options/arguments to the cmdline. The file ```$HOME/.ilivalidator``` is ignored and only used by the GUI (to ensure a consistent behaviour of the cmdline).

**Comment by Pierre-de-la-Verre** [comment]
Thanks; it was not clear for me.
