### ISSUE TITLE
Attempting to disable geometry validation with no success

### ISSUE THREAD

**Issue by gacarrillor** [claeis/ilivalidator#272]
I'd like to disable geometry validations on my data. Namely, I'd like to skip these kind of errors:

-------------------------------------
_Error: line 55021: Submodelo_Insumos_Gestor_Catastral_V1_0.Datos_Gestor_Catastral.GC_UnidadConstruccion: tid 00521146-67d1-4c28-8885-3fe32853d5c4: duplicate coord at (4851517.718, 2089778.456, 0.0)_

_Error: line 218984: Submodelo_Insumos_Gestor_Catastral_V1_0.Datos_Gestor_Catastral.GC_Terreno: tid b57f7f02-2c2b-4dc6-b781-c3bc79c486a2:   invalid ring lines_

_Error: ISO19107_PLANAS_V3_0.GM_Surface2DListValue.value: Overlay coord1 (4845088.354, 2093178.902), coord2 (4845091.755, 2093176.858), tids 232db8b1-316b-439e-8ad5-97c5adcb38c5, 232db8b1-316b-439e-8ad5-97c5adcb38c5_

-------------------------------------

I've used:
 + `iliValidator` along with this [config file](https://gist.github.com/gacarrillor/7dc0fc5d66eba6a780d8f4569cbb054d).
 + `ili2db`'s `export` and `validate` operations along with `--skipGeometryErrors`.

but I keep getting either `...validation failed` or `...export failed`, depending on the tool.

Here is a log file (option `--trace`) from iliValidator: [log_ilivalidator.txt](https://github.com/claeis/ilivalidator/files/5159380/log_ilivalidator.txt)
Here is a log file (option `--trace`) from ili2db: [log.txt](https://github.com/claeis/ilivalidator/files/5159362/log.txt)

Sample data: [test_03.xtf.zip](https://github.com/claeis/ilivalidator/files/5159355/test_03.xtf.zip).
ili models: [LADM-COL](https://github.com/SwissTierrasColombia/LADM_COL/releases/download/1.0/Modelo_Aplicacion_LADMCOL_Levantamiento_Catastral_V1_0.zip)

Am I missing something?

------------------
Tool versions:
  + ilivalidator-1.2.1-20170420 (ili2c-4.7.6-20171229)
  + ili2pg-4.4.3 (ili2c-5.1.0-20200501)

**Comment by beistehen** [comment]
I am not aware of an option to suppress these kind of errors in ilivalidator.
