### ISSUE TITLE
Header info: Which model is taken from which file?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#273]
The header of my log-file looks like this:

**Info: ilidirs <c:\data\Interlis_Checkergrundlagen\SIA_2018\>
Info: lookup model <SIA405_LKMap_2015_LV95> 2.3 in repository <c:\data\Interlis_Checkergrundlagen\SIA_2018\/>
Info: lookup model <SIA405_Base> 2.3 in repository <c:\data\Interlis_Checkergrundlagen\SIA_2018\/>
Info: lookup model <Units> 2.3 in repository <c:\data\Interlis_Checkergrundlagen\SIA_2018\/>
Info: lookup model <Base> 2.3 in repository <c:\data\Interlis_Checkergrundlagen\SIA_2018\/>
Info: ilifile <c:\data\Interlis_Checkergrundlagen\SIA_2018\41.ili>
Info: ilifile <c:\data\Interlis_Checkergrundlagen\SIA_2018\2.ili>
Info: ilifile <c:\data\Interlis_Checkergrundlagen\SIA_2018\6.ili>
Info: ilifile <c:\data\Interlis_Checkergrundlagen\SIA_2018\32.ili>`**

It is not clear which model is taken from which file. It is possible that different models are stored in same file or that same models are stored in different file, so a precise message (the information already exists) like
`Modell X used from c:\data\y.ili`
would be better ..

**Comment by claeis** [comment]
The list of ili-files is reported before these files are read (so at that point in time, it is not known which file contains which model). This is done, to help in case of stranger errors and failures to see what was the input to the failure.

And a data validation tool, is the wrong place to report about the model elements. It should report about the data (which is done). A report about the models/topics in a ili-file might be a new feature in ili2c.

**Comment by Pierre-de-la-Verre** [comment]
Hmm - I didn't mean to report "what model is where", I meant "validation was made on base of model abc from file xyz". I suppose the software already "knows this", so maybe it need only to be written.

But it is not the most important stuff ..
