### ISSUE TITLE
Fehler im AREA Check

### ISSUE THREAD

**Issue by svakac** [claeis/ilivalidator#274]
Wir haben ein Problem mit dem IliValidator AREA Check. In der Datei LP_LESPBasel_PGDM_V1_0_LV95_inKraft.xtf befindet sich die Klasse Laermempfindlichkeitstufe, welche als AREA definiert ist. In der Klasse hat es zwei Flächen die sich deutlich überlagern (xtf_id 44329665831436602841251841 mit xtf_id 43573515346818720463863809). In den beiliegenden Logfiles vom IliValidator Version 1.11.2 und auch mit der neuesten Version 1.11.6 ist erkennbar, dass der Fehler nicht bemerkt wird.

[CheckFehler_IliValidator.zip](https://github.com/claeis/ilivalidator/files/5224415/CheckFehler_IliValidator.zip)

**Comment by edigonzales** [comment]
Ist mit 1.11.7 gefixed. https://github.com/claeis/ilivalidator/issues/263 Es hat auch eine gepatchte Version drin zum Ausprobieren.

War ein Problem, falls ein Polygon komplett innerhalb eines anderen liegt.

**Comment by svakac** [comment]
Dankeschön. Wann ist mit 1.11.7 zu rechnen?

**Comment by edigonzales** [comment]
Kann eventuell @claeis beantworten.

Snaphot releases gibts hier: http://jars.interlis.ch/ch/interlis/ilivalidator/1.11.7-SNAPSHOT/ilivalidator-1.11.7-20200824.132225-5-bindist.zip
