### ISSUE TITLE
Unit mm not checked for integer?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#275]
I have this XTF-snippet:

      <SIA405_LKMap_2015_LV95.SIA405_LKMap.LKLinie TID="ch...">
        <OBJ_ID>ch...</OBJ_ID>
        <Metaattribute>
          <SIA405_Base_LV95.Metaattribute>
            <Datenherr>Politische ...</Datenherr>
            <Datenlieferant>....</Datenlieferant>
            <Letzte_Aenderung>20170718</Letzte_Aenderung>
          </SIA405_Base_LV95.Metaattribute>
        </Metaattribute>
        <Eigentuemer>Politische ...</Eigentuemer>
        <Lagebestimmung>ungenau</Lagebestimmung>
        <Status>in_Betrieb</Status>
        <Breite>60.3</Breite>
        <Linie>
          <POLYLINE>
         
some values ....
          </POLYLINE>
        </Linie>
        <Objektart>Wasser.Leitung</Objektart>
      </SIA405_LKMap_2015_LV95.SIA405_LKMap.LKLinie>

Breite is used for values in mm, and I get this error from another check-software:
**unable to convert attribute Breite to type INTEGER**

Do I use wrong settings?

**Comment by edigonzales** [comment]
- Kannst du einen Beispieldatensatz inkl. Modell hochladen?
- Wie lautet der ilivalidator-Befehl, den du verwendest?
- Was meinst du mit "Breite is used in mm, and I get this error, bit not from ilivalidator"

**Comment by beistehen** [comment]
The error message is from ig/Check, which is used by VSA and some cantonal check services (e. g. TG in this case, my guess).
See #229 
ig/Check and ilivalidator have different opinions whether a range of `0..10` means that only INTEGERS are allowed.
It is marked as a difference/bug in Test Suite.

**Comment by Pierre-de-la-Verre** [comment]
@beistehen 
thanks - that's exactly what I mean.

**Comment by claeis** [comment]
Nothing to decide....see RefHB 3.3.11.4: 

> Sie können auch mit höherer
Genauigkeit transferiert werden als durch den Wertebereich verlangt.

**Comment by Pierre-de-la-Verre** [comment]
Thanks
