### ISSUE TITLE
UUIDOID definition: missing error message

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#278]
Im beiliegenden Modell ist folgendes definiert:
  UUIDOID = OID TEXT*36;
In der ebenfalls beiliegenden .xtf-Datei beträgt die Länge des UUIDOID aber 38 Zeichen. Der ilivalidator sollte reklamieren.
[UUIDOID.zip](https://github.com/claeis/ilivalidator/files/5282682/UUIDOID.zip)

**Comment by beistehen** [comment]
Der ilivalidator nimmt an, dass mit UUIDOID immer diejenige Definition aus dem internen INTERLIS-Datenmodell gemeint ist. Im obigen Fall wird jedoch nicht die interne Definition verwendet, sondern mit `UUIDOID = OID TEXT*36;` eine eigene erzeugt.

Testhalber habe ich im Modell folgendes angepasst:

- `  IMPORTS UNQUALIFIED INTERLIS;` ergänzt
- `UUIDOID = OID TEXT*36;` entfernt

Danach meldet ilivalidator den Fehler korrekt:
`Error: line 11: swissTLMRegio_***skipped***: tid 176805: value <{4DB10515-1AC1-477D-AEF0-4C515C10CD88}> is not a valid UUID in attribute UUID`

Das Problem ist im Code wohl [hier](https://github.com/claeis/iox-ili/blob/6a4b129461aca40facb46f143c05aa8f6b0f7878/src/main/java/ch/interlis/iox_j/validator/Validator.java#L509) zu finden. Die Länge der OID wird scheinbar nicht überprüft.

Ich empfehle, für die UUIDOID auf das interne INTERLIS-Modell zu referenzieren. Da wird nämlich der korrekte Aufbau der UUID geprüft, nicht nur die Länge. Die geschweiften Klammern würden dann ebenfalls beanstandet, auch wenn die Länge korrekt wäre.

**Comment by beistehen** [comment]
Die Codierung von OIDs als Datentyp ist definiert als
```
[ TAG ( %AttributeName%,
        'OID=' XML-ID )
  ETAG ( %AttributeName% ) ]
```
(Quelle: RefHB 2.3, Kapitel 3.3.11.16)

Ein Datenmodell enthält folgende Attribut-Definition:
```
UUID: MANDATORY INTERLIS.UUIDOID;
```

neue Erkenntnis: ilivalidator lässt folgende beiden Codierungen zu:
```xml
<UUID OID="4DB10515-1AC1-477D-AEF0-4C515C10CD88" />   <!-- als XML-Attribut, gemäss RefHB -->
<UUID>4DB10515-1AC1-477D-AEF0-4C515C10CD88</UUID>     <!-- als XML-Wert, nicht zulässig gemäss RefHB -->
```
Grund: beim Parsen des XTF wird nicht unterschieden, ob die Daten aus einem XML-Attribut oder aus einem XML-Wert stammen. Falls ein XML-Attribut namens `OID` vorhanden ist, so wird dieses genommen und der Rest ignoriert (siehe [hier im Code](https://github.com/claeis/iox-ili/blob/89b2606323b26e6195b8c7bf2717dd4024032b92/src/main/java/ch/interlis/iom_j/xtf/impl/MyHandler.java#L734)). Das führt dazu, dass folgendes XML-Element ebenfalls fälschlicherweise valide ist:
```xml
<UUID OID="4DB10515-1AC1-477D-AEF0-4C515C10CD88">Dieser XML-Wert wird nicht validiert</UUID>
```

PS. In **INTERLIS 2.4** wird der OIDType wie alle anderen Datentypen ebenfalls als XML-Wert codiert und nicht mehr als XML-Attribut :ok_hand:
