### ISSUE TITLE
New tab "Hilfe"

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#279]
Analog dem Compiler und dem UML/INTERLIS-Editor sollte auch der ilivalidator einen Reiter "Hilfe" erhalten, wo einerseits unter dem Menüpunkt "Hilfe" ein Link auf die Online-Dokumentation in GitHub eingefügt würde und unter "About" die aktuelle, aufgerufene Version angegeben ist.
Wenn mit verschiedenen Versionen des ilivalidators gearbeitet wird, muss nicht zuerst eine Dateiprüfung vorgenommen werden um die Version festzustellen, sondern sie wäre direkt unter "About" abrufbar.

**Comment by Pierre-de-la-Verre** [comment]
Aus reiner Neugier: warum arbeitet man mit verschiedenen Versionen?

Schönes Wochenende an alle!

**Comment by ltzur** [comment]
Als Koordinationsstelle für Geoinformation der Bundesverwaltung (KOGIS) haben wir für die INTERLIS-Werkzeuge Wartungsverträge und verfolgen die Entwicklung dieser Tools aktiv. Zudem haben wir eine Test Suite entwickelt, wo wir die die verschiedenen Versionen der beiden Prüfwerkzeuge ilivalidator und iG/Check direkt vergleichen können.

**Comment by Philippluca** [comment]
@claeis Ich werde dieses Issue übernehmen.
