### ISSUE TITLE
Unclear messages for wrong batch-calls

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#282]
low priority

I have a command line to a long file path with blank, e.g.

`java -jar ilivalidator.jar --config config.toml --log mylog.log     d:\Program Files\ilivalidator\x y.xtf`

When I make an error and forget to quote the filename (because of the blanks), then I get the log like this

```
Info: Start date 2020-10-01 14:09
Info: maxMemory 6524928 KB
Info: dataFile <D:\Program>
Info: dataFile <Files\ilivalidator\x>
Info: dataFile <y.xtf>
....
```
That's all - the program quits. A message like "Defined Datafile 'D:\Program' was not found or something else could help the user to find his mistake

**Comment by claeis** [comment]
No, that's not all. At the end it states, that it failed to read the file.

    Error: java.io.FileNotFoundException: D:\Program (The system cannot find the file specified)

In general: Info messages are not error message, but messages that show what the program is going to do or what it did (or what input it uses).
