### ISSUE TITLE
Download of 1.11.8?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#283]
Maybe I don't understand Github enough, but from interlis.ch I can download the 1.11.8-ZIP.

Here, at https://github.com/claeis/ilivalidator/releases, I find for ..
- 1.11.6: software + 2 x source
- 1.11.7: 2 x source
-1.11.8: a small entry with no files

Where is my mistake?
![grafik](https://user-images.githubusercontent.com/13277944/95085154-202af980-071f-11eb-87fd-6c03b92185bd.png)

**Comment by claeis** [comment]
I stopped to publish the binary file at github. It is now [here](https://downloads.interlis.ch/ilivalidator)

**Comment by Pierre-de-la-Verre** [comment]
OK, thanks. It was not clear for me ..
