### ISSUE TITLE
"no area-ref to polygon" in "donut-area"

### ISSUE THREAD

**Issue by KunoEpper** [claeis/ilivalidator#286]
**Situation**
Thema Bodenbedeckung. In einer Gemeinde umschliesst eine Strassenfläche in Form einer Schliefe eine Restfläche. Der ilivalidator gibt in dieser Situation bei den Linienzügen, welche die Restfläche umschliessen, den Fehler "no area-ref to polygon" aus.

**Vemutung**
Weil die durch die Strasse umschlossene Fläche (Donut-Fläche) zur Restfläche gehört, dürfte kein Fehler ausgewiesen werden.

**Anhang**
- AV_RIEMENSTALDEN - BoFlaeche.ITF: ITF-Datei; auf die Bodenbedeckung reduziert
- AV_RIEMENSTALDEN - BoFlaeche.log: Log-Datei ilivalidator
- DM01AV_UR_SZ_OW_NW_V24_01_LV95.ili: Modell-Datei
- FME Data-Inspector.png: Abbildung aus FME-Data-Inspector
- WebGIS.png: Abbildung WebGIS

[data.zip](https://github.com/claeis/ilivalidator/files/5406433/data.zip)

**Comment by edigonzales** [comment]
Hast du es mit `--allowItfAreaHoles` probiert? Option ist glaub genau aus solchen Gründen entstanden.

https://github.com/claeis/ilivalidator/blob/master/docs/ilivalidator.rst

**Comment by KunoEpper** [comment]
Danke, damit hat sich das "Problem" gelöst!

`Info: ...validation done`
