### ISSUE TITLE
Verhalten INTERLIS. isEnumSubVal, falls Attributwert nicht vorhanden ist

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#288]
`MANDATORY CONSTRAINT isEnumSubVal(FunktionHierarchisch, #SAA); `

Im Transferfile ist `FunktionHierarchisch` nicht vorhanden. Ilivalidator meldet keinen Fehler. Ist das korrektes Verhalten? 

Wenn `FunktionHierarchisch` mit einem falschen Subvalue vorhanden ist, wird ein Fehler gemeldet. Wenn `FunktionHierarchisch` mit einem korrekten Subvalue vorhanden ist, wird kein Fehler gemeldet.

Eventuell etwa hier: https://github.com/claeis/iox-ili/blob/32a4e5fee0bad8e807268df5842953f162874c17/src/main/java/ch/interlis/iox_j/validator/functions/Interlis.java#L74

**Comment by edigonzales** [comment]
Beobachtung: 

```
         MANDATORY CONSTRAINT DEFINED (Finanzierung)
                                                 OR
                                                 isEnumSubVal(FunktionHierarchisch, #SAA);
```

Falls `FunktionHierarchisch` nicht vorhanden ist, wird der gesamte Constraint nicht ausgewertet. D.h. falls `FunktionHierarchisch` _und_ `Finanzierung` nicht vorhanden ist, wird kein Fehler gemeldet.

**Comment by claeis** [comment]
Im RefHB 2.4 ist das präzisiert:

> Ist eine Konsistenzbedingung (MANDATORY CONSTRAINT) nicht berechenbar (weil z.B. ein Attribut beteiligt ist, dessen Wert 
> undefiniert ist, oder der Divisor 0 beträgt) so gilt die Konsistenzbedingung für das aktuelle Objekt als erfüllt.

So wird es vom ilivalidator auch für ili 2.3 interpretiert.

Darum gibt es keine Fehlermeldung.

**Comment by edigonzales** [comment]
Heisst das, dass man sich im Kernteam einig ist (auch für 2.3) oder nicht einig war und es darum jetzt präzisierte?
