### ISSUE TITLE
Error messages for functions

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#29]
When I add some additional constraints with built-in or custom functions, the error messages are hard to read, e.g.:

`Error: line 50: FunctionTests.Control_points.Control_point: tid def3a9bc-1f0d-4430-b03d-cf421709f171: Mandatory Constraint FunctionTests.Control_points.Control_point.Constraint5 is not true.`

Will there be some more information like FUNCTION name? Or will it be possible to add some meta comments, which will be in the log file?

**Comment by claeis** [comment]
Only Constraints trigger validation messages, but not functions. Functions can only be evaluated. It will be possible to override the default ("Mandatory Constraint ... is not true") with a user defined messages (see #14)
