### ISSUE TITLE
implement --metaConfig

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#290]
`--config gb2av.toml` durchsucht die Datarepositories und lädt die entsprechende Datei herunter. 

tbd:
- Dateiname vs. Konfigurationsname
- ...

**Comment by claeis** [comment]
Nicht der Dateiname, das wäre falsch. Es müsste aus Sicht Datenrepositories die BasketId sein (die in dem Kontext der Validator-Konfigurationsname wäre).

Aber es braucht m.E. Werkzeug-übergreifend betrachtet eine weitere (Konfigurations-)ebene, so dass man z.B. auch die in dieser Konfiguration spezifischen Kataloge, oder Styles usw. konfigurieren kann. Und da muss man dann wahrscheinlich auch eine Basis-Konfiguration überschreiben können, evtl. sogar mehrere Basiskonfigurationen mischen.

**Comment by claeis** [comment]
see claeis/iox-ili#91
