### ISSUE TITLE
Bug: check-repo-data

### ISSUE THREAD

**Issue by rschertenleib** [claeis/ilivalidator#291]
java -jar ilivalidator.jar --check-repo-data http://models.geo.gl.ch/ 

ergibt die Fehlermeldung, dass das File nicht gefunden werden kann (Falsche Syntax für Dateinamen/Verzeichnisnamen), obwohl in diesem Repository an diesem Pfad Daten vorliegen.

_C:\Software\ilivalidator-1.11.8>java -jar ilivalidator.jar --check-repo-data http://models.geo.gl.ch/
Info: ilivalidator-1.11.8-ca0d0f2ac7e23317edfa29f33dcfa8ed87e75094
Info: ili2c-5.1.4-74358b39131185c7a0b8dd2e9c5a5b548a9f385a
Info: iox-ili-1.21.3-8f71ffea01602330414e5314350aa3f1d33d2897
Info: User <Administrator>
Info: Start date 2020-12-15 12:07
Info: maxMemory 3714048 KB
Info: dataFile <http://models.geo.gl.ch//xml/GL_Hpm_Catalogues_V1_1.xml>
Error: java.io.FileNotFoundException: http:\models.geo.gl.ch\xml\GL_Hpm_Catalogues_V1_1.xml (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch)
Error:   http:\models.geo.gl.ch\xml\GL_Hpm_Catalogues_V1_1.xml (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch)_

**Comment by edigonzales** [comment]
Ich glaube das Problem liegt hier: https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/IoxUtility.java#L53 

Das File-Objekt wird mit dem URL-String "http://models.geo.gl.ch//xml/GL_Hpm_Catalogues_V1_1.xml" instanziert, was nicht funktioniert.

Siehe auch die komische "URL" in der Fehlermeldung: "http:\...".

**Comment by claeis** [comment]
Nein, Problem ist anderswo
