### ISSUE TITLE
Question: Anyone here who could validate a XTF-file with 1.4 GB ?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#293]
Anyone here who could validate a XTF-file with 1.4 GB ?
And if "yes": What was your environment and your setting?

Thanks!

**Comment by kuhnpa** [comment]
Das grösste XTF bei uns war bisher knapp 800 MB.
64-Bit Java-Version. PC mit ordentlich RAM. RAM beim Aufruf zuweisen. Im Beispiel sind es 12 GB RAM:
`java -Xmx12g -jar ....`

**Comment by edigonzales** [comment]
Yes. 2.3GB XTF with `-Xmx2g`. But it is a really simple model (no associations at all, no AREA constraints). So I _guess_ it depends not only on the actual file size (btw: pretty print vs minified could make a huge difference) but also on the model, e.g. AREA constraints, ...

There were some improvements made: https://github.com/claeis/iox-ili/commit/87336c2999188e7dae6fa088e02deab5cdec7cf8 

These improvements should be released. So if you are using the newest release, it does not solve your problem.

What model? What is your environment / are your settings? Can you share the data?

**Comment by Pierre-de-la-Verre** [comment]
Thanks. We will try ...

**Comment by beistehen** [comment]
> These improvements should be released. So if you are using the newest release, it does not solve your problem.

Looks like the improvements were released in `iox-ili v1.21.2`, which is used by ilivalidator starting in v1.11.7 according to the [readme](https://github.com/claeis/ilivalidator/blob/1179e1733a4ea0c8da9c8b5e2dc9ac98c552b8d3/docs/CHANGELOG.txt#L22). So running the lastest build of ilivalidator should use the improved memory management. Give it a try :wink:

**Comment by edigonzales** [comment]
Sorry, yes. @beistehen is right. 

Can you share some more details? Does the validation finish the "first validation pass" and hangs on the "second validation pass"? Do you have some log files? Can you share the data?

**Comment by Pierre-de-la-Verre** [comment]
Hi

here is the info and the data I got from my colleague:

_The validation of the xtf-file (1.4 GB) succeeds, if area validation is disabled. Then validation takes half an hour with 64-Bit Java, –Xmx24G and v1.11.9._
_If area validation is enabled, the process – with same settings – stops after approx. 6 hours, during checks of area topology._

_The validation is executed for Kanton Thurgau containing current model NATURGEFAHREN_TG04. Data can therefore not contributed. But resulting log-files (with and without area validation) and ili-file are enclosed._ 

_These tests show, that validation does not fail with constraints, associations etc., but with area topology for huge polygons containing close vertices._

**Comment by edigonzales** [comment]
Funny thing is that the AREA validation for Naturgefahren is also a challenge for us... We noticed that it also needs a lot of disk space in the tmp directory. Can you take a look if it fills up your tmp directory during the AREA validation?

At the end of the day, I think it's something you have to address to @claeis.

**Comment by claeis** [comment]
ili2 AREA validation is memory intensive (nr of polygons, nr of boundaries, nr of vertices, nr of intersections are key numbers). Improvements are possible, but would require some effort. (And would slow down the overall performance of the validation).

**Comment by Pierre-de-la-Verre** [comment]
What is the current state of the topic?
Maybe the first simple step could be a message like "Your file is larger than xxx MB; consider to switch of the 'area validation' because of ...."

**Comment by claeis** [comment]
The filesize is more or less irrelevant.
