### ISSUE TITLE
Bezug zu Objekt in anderem BID nicht erkannt

### ISSUE THREAD

**Issue by sjib** [claeis/ilivalidator#294]
Ich versuche folgenden Testdatensatz zu validieren und verstehe nicht, warum ich diese Fehlermeldung erhalte - ich mache die Referenz ja auf den anderen Basket mit BID = fk11abk6w70lrfno und nicht fk11abk6w70lrfnh

Error: line 37: VSA_KEK_2019_LV95.KEK.Untersuchung: tid fk11abk6w70lohup: No object found with OID ch080qwzPR000017 in basket fk11abk6w70lrfnh.

`<?xml version="1.0" encoding="UTF-8"?>  
<TRANSFER xmlns="http://www.interlis.ch/INTERLIS2.3">    
  <HEADERSECTION VERSION="2.3" SENDER="VSA">            
    <MODELS>
      <MODEL NAME="VSA_KEK_2019_LV95" VERSION="30.12.2020" URI="http://www.vsa.ch/models" />
      <MODEL NAME="SIA405_ABWASSER_2015_LV95" VERSION="17.04.2018" URI="http://www.sia.ch/405" />
      <MODEL NAME="SIA405_Base_LV95" VERSION="05.10.2018" URI="http://www.interlis.ch/models" />
      <MODEL NAME="Base_LV95" VERSION="05.10.2018" URI="http://www.interlis.ch/models" />
    </MODELS>
    <ALIAS>
      <ENTRIES FOR="VSA_KEK_2019_LV95" />
    </ALIAS>
    <COMMENT>Dataset Generated by Test</COMMENT>           
  </HEADERSECTION>
  <DATASECTION>
    <SIA405_ABWASSER_2015_LV95.SIA405_Abwasser BID="fk11abk6w70lrfno">
	<SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation TID="ch080qwzPR000017">
	<OBJ_ID>ch080qwzPR000017</OBJ_ID>
        <Metaattribute>
			<SIA405_Base_LV95.Metaattribute>
				<Datenherr>Testfirma</Datenherr>
				<Datenlieferant>KINS</Datenlieferant>
				<Letzte_Aenderung>20210119</Letzte_Aenderung> 
			</SIA405_Base_LV95.Metaattribute>
		</Metaattribute>
      <Bemerkung>Bemerkung zur Firma</Bemerkung>
      <Bezeichnung>Testfirma</Bezeichnung>
	</SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation>
	</SIA405_ABWASSER_2015_LV95.SIA405_Abwasser>
	<VSA_KEK_2019_LV95.KEK BID="fk11abk6w70lrfnh" KIND="UPDATE">
      <VSA_KEK_2019_LV95.KEK.Untersuchung TID="fk11abk6w70lohup">
        <OBJ_ID>fk11abk6w70lohup</OBJ_ID>
        <Metaattribute>
			<SIA405_Base_LV95.Metaattribute>
				<Datenherr>Testfirma</Datenherr>
				<Datenlieferant>KINS</Datenlieferant>
				<Letzte_Aenderung>20210119</Letzte_Aenderung>
			</SIA405_Base_LV95.Metaattribute>
		</Metaattribute>
		<Art>Untersuchung</Art>
		<Ausfuehrender>Herr Mustermann</Ausfuehrender>
        <Bemerkung>Testbemerkungen zum Untersuch</Bemerkung>
        <Bezeichnung>5.1-5.2</Bezeichnung>
        <Datengrundlage></Datengrundlage>
        <Dauer>1</Dauer>
        <Detaildaten></Detaildaten>
        <Ergebnis></Ergebnis>
        <Grund>Zustandskontrolle</Grund>
        <Kosten>0</Kosten>
        <Status>ausgefuehrt</Status>
        <Zeitpunkt>20201025</Zeitpunkt>
        <bisPunktBezeichnung>5.1</bisPunktBezeichnung>
        <Erfassungsart>Kanalfernsehen</Erfassungsart>
        <Fahrzeug>Testfahrzeug</Fahrzeug>
        <Geraet>Testkamera</Geraet>
        <Inspizierte_Laenge>0</Inspizierte_Laenge>
        <Videonummer></Videonummer>
        <vonPunktBezeichnung>5.2</vonPunktBezeichnung>
        <Witterung>schoen_trocken</Witterung>
	<Ausfuehrende_FirmaRef REF="ch080qwzPR000017" BID="fk11abk6w70lrfno" CONSISTENCY="INCOMPLETE"></Ausfuehrende_FirmaRef>
      </VSA_KEK_2019_LV95.KEK.Untersuchung>
etc.
   </VSA_KEK_2019_LV95.KEK>
  </DATASECTION>
</TRANSFER>`

Ist diese Notation falsch?

`<Ausfuehrende_FirmaRef REF="ch080qwzPR000017" BID="fk11abk6w70lrfno" CONSISTENCY="INCOMPLETE">`

**Comment by edigonzales** [comment]
Einen Unterschied ist, dass du in

```
ASSOCIATION Untersuchung_HaltungspunktAssoc =    !! Assoziation
  HaltungspunktRef (EXTERNAL) -- {0..1} SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt;
  Untersuchung_HaltungspunktAssocRef -- {0..*} Untersuchung;
END Untersuchung_HaltungspunktAssoc;
```

die Rolle EXTERNAL definierst. Bei

```
ASSOCIATION Erhaltungsereignis_Ausfuehrende_FirmaAssoc =    !! Assoziation
  Ausfuehrende_FirmaRef  -- {0..1} Organisation;
  Erhaltungsereignis_Ausfuehrende_FirmaAssocRef -- {0..*} Erhaltungsereignis;
END Erhaltungsereignis_Ausfuehrende_FirmaAssoc;
```
nicht. Oder würde es reichen, wenn "Organisation" qualifiziert ist? Wie weiss man, ob "Organisation" aus dem KEK-Modell stammt oder aus dem SIA-Modell?

**Comment by beistehen** [comment]
> Oder würde es reichen, wenn "Organisation" qualifiziert ist? Wie weiss man, ob "Organisation" aus dem KEK-Modell stammt oder aus dem SIA-Modell?

Sobald das Zielobjekt in einem anderen Basket zu finden ist, muss die Rolle mit `(EXTERNAL)` gekennzeichnet sein. Und die Zielklasse muss voll qualifiziert sein: `SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation`.

Die Notation mit `REF="xxx" BID="yyy"` ist korrekt, der Teil mit `CONSISTENCY...` ist falsch und sollte entfernt werden.

**Comment by sjib** [comment]
Danke. Mit der Modellkorrektur funktioniert es: 

`Ausfuehrende_FirmaRef (EXTERNAL) -- {0..1} SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation;`

statt

`Ausfuehrende_FirmaRef  -- {0..1} Organisation;`


`ASSOCIATION Erhaltungsereignis_Ausfuehrende_FirmaAssoc =    !! Assoziation
  Ausfuehrende_FirmaRef (EXTERNAL) -- {0..1} SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation;
  Erhaltungsereignis_Ausfuehrende_FirmaAssocRef -- {0..*} Erhaltungsereignis;
END Erhaltungsereignis_Ausfuehrende_FirmaAssoc;`

**Comment by claeis** [comment]
To be able to import the data with ili2db, the referenced EXTERNAL objects (SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation) must have a stable and unique TID/OID.
