### ISSUE TITLE
AREA topology not validated if validation of SURFACE topology failed 

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#296]
Falls bereits gewisse Fehler bei der "einzelnen" Geometrieprüfung auftreten, erscheint die Meldung, dass die AREA-Prüfung nicht durchgeführt wird: "AREA topology not validated, validation of SURFACE topology failed in attribute Geometrie".

Aber es erscheint trotzdem die Meldung: "Info: validate AREA SO_KSTA_Landwert_20210202.Landwerte.Landwert.Geometrie..." und ilivalidator rechnet und rechnet (jedenfalls gefühlt).

Ist das so? Oder macht er nur einen Teil der AREA-Prüfung nicht?

**Comment by edigonzales** [comment]
@edigonzales Gutes Beispiel? FFF oder Landwerte (wobei die sind beide korrigiert). Vorgehensweise erläutern und faken.

**Comment by claeis** [comment]
Wenn die SURFACE Valdierung fehlschlägt, sollte keine Zeit mehr mit AREA Validierung verbraten werden.

**Comment by edigonzales** [comment]
Daten ohne Fehler: `time java -jar /Users/stefan/apps/ilivalidator-1.11.11/ilivalidator-1.11.11.jar ch.so.alw.fruchtfolgeflaechen_edit_orig.xtf 
297.68s user 234.84s system 101% cpu 8:45.48 total`

Daten mit Fehler: `time java -jar /Users/stefan/apps/ilivalidator-1.11.11/ilivalidator-1.11.11.jar ch.so.alw.fruchtfolgeflaechen_edit.xtf 381.04s user 235.49s system 116% cpu 8:47.79 total`

Daten mit Fehler und explizitem Ausschalten der Area-Validierung: `time java -jar /Users/stefan/apps/ilivalidator-1.11.11/ilivalidator-1.11.11.jar --disableAreaValidation ch.so.alw.fruchtfolgeflaechen_edit.xtf 41.55s user 0.51s system 118% cpu 35.580 total`

Log bei "Daten mit Fehler":
```

Info: assume unknown external objects
Info: first validation pass...
Error: SO_ALW_Fruchtfolgeflaechen_Publikation_20220110.Inventarflaechen.Fruchtfolgeflaeche.Geometrie: dangle tid 16250
Info: AREA topology not validated, validation of SURFACE topology failed in attribute Geometrie
Info: second validation pass...
Info: validate AREA SO_ALW_Fruchtfolgeflaechen_Publikation_20220110.Inventarflaechen.Fruchtfolgeflaeche.Geometrie...
Info: ch.so.alw.fruchtfolgeflaechen_edit.xtf: SO_ALW_Fruchtfolgeflaechen_Publikation_20220110.Inventarflaechen BID=SO_ALW_Fruchtfolgeflaechen_Publikation_20220110.Inventarflaechen
Info:   11355 objects in CLASS SO_ALW_Fruchtfolgeflaechen_Publikation_20220110.Inventarflaechen.Fruchtfolgeflaeche
Info:     519 objects in CLASS SO_ALW_Fruchtfolgeflaechen_Publikation_20220110.Inventarflaechen.Statistik
Info: ...validation failed
```
[ch.so.alw.fruchtfolgeflaechen_edit.xtf.zip](https://github.com/claeis/ilivalidator/files/7936191/ch.so.alw.fruchtfolgeflaechen_edit.xtf.zip)

[ch.so.alw.fruchtfolgeflaechen_edit_orig.xtf.zip](https://github.com/claeis/ilivalidator/files/7936196/ch.so.alw.fruchtfolgeflaechen_edit_orig.xtf.zip)

**Comment by patrickackermann** [comment]
Das aktuelle Verhalten ist, dass bei der AREA Validierung jene Geometrien, die Fehler haben ignoriert werden. Die Info-Meldung ist etwas irreführend.

Ich habe ein minimales Beispiel erstellt, das das verhalten veranschaulicht:
[AREA_invalid_geometry.zip](https://github.com/claeis/ilivalidator/files/9470054/AREA_invalid_geometry.zip)

```
Info: first validation pass...
Error: AreArea_Model.Topic.AreArea_Class.geom1: dangle tid 1
Info: AREA topology not validated, validation of SURFACE topology failed in attribute geom1
Info: second validation pass...
Info: validate AREA AreArea_Model.Topic.AreArea_Class.geom1...
Error: AreArea_Model.Topic.AreArea_Class: tid 2: Intersection coord1 (550.000, 600.000), tids 2, 3
Error: AreArea_Model.Topic.AreArea_Class: tid 2: Intersection coord1 (600.000, 550.000), tids 2, 3
Error: failed to validate AREA AreArea_Model.Topic.AreArea_Class.geom1
Info: object count 3 (structured elements 0)
```

@edigonzales Ich ändere das verhalten so, dass die AREA Topologie eines Attributes nicht validiert wird, wenn ein Objekt bei diesem Attribut die Surface topology validation nicht erfüllt.
