### ISSUE TITLE
Test Classes not properly working

### ISSUE THREAD

**Issue by leader80** [claeis/ilivalidator#3]
Hi Claeis,

I just cloned and ran you project but unfortunatley I'm getting several issues with the test class, is that normal?

please find here the console log:

Info: ilivalidator-0.3.0-20160905
Info: ili2c-4.5.23-20160708
Info: xtfFile <test/data/Beispiel1b.itf>
Info: ilidirs <%ITF_DIR>
Info: lookup model <Beispiel1> in repository <C:\Users\t141405\neon_workspace\ilivalidator\test\data>
Info: ilifile <C:\Users\t141405\neon_workspace\ilivalidator\test\data\Beispiel1.ili>
Info: validate data...
Error: line 9: Beispiel1.Bodenbedeckung.GebaeudeArt: tid 3: Attribute Art requires a value
Error: line 10: Beispiel1.Bodenbedeckung.GebaeudeArt: tid 4: Attribute Art is length restricted to 6
Warning: Beispiel1.Bodenbedeckung.BoFlaechen 205: unexpected code <22> for attribute Art; read without mapping
Error: java.lang.NullPointerException

Best regards,
Cheers
G.

**Comment by claeis** [comment]
can't reproduce
