### ISSUE TITLE
Custom functions support for ili2.2

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#30]
I tried to add some custom validation function for a ili2.2 model (find attached). Compiler does not complain but ilivalidator does: 

`Error: line 8: GB2AV.Mutationstabelle.Liegenschaft: tid z48f364f300002077: Function is not yet implemented.` 

I was able to track it down in Validator.java (iox-ili):

`String javaClassname=validationConfig.getConfigValue(functionQname, ValidationConfig.IMPL_JAVA);`

It always returns null. Not sure if meta attributes are officially supported in ili2.2 or are implemented.

[KS3-20060703.ili.zip](https://github.com/claeis/ilivalidator/files/769384/KS3-20060703.ili.zip)

**Comment by claeis** [comment]
The ili language only allows to declare functions. Therefor the compiler will never complain about not implemented functions.
But will change interface so that no meta attribute is required. see #12
