### ISSUE TITLE
Interlis 2.4 xtf: unexpected start element .....

### ISSUE THREAD

**Issue by threalslimtobeeee** [claeis/ilivalidator#305]
I successfully transformed Data (.xtf) from INTERLIS 2.3 to 2.4. 

The ilivalidator returns no error with this data structure (note the space before each `<geom:coord>` ):

`<Revitalisierung_Seen_V2:Uferlinie_Geometrie ili:tid="22"><Revitalisierung_Seen_V2:UferTeilstueck><geom:polyline>
 <geom:coord><geom:c1>2716790.5120285717</geom:c1><geom:c2>1226221.6561714285</geom:c2></geom:coord>
 <geom:coord><geom:c1>2716791.177</geom:c1><geom:c2>1226221.038</geom:c2></geom:coord>
 <geom:coord><geom:c1>2716792.668666667</geom:c1><geom:c2>1226219.055857143</geom:c2></geom:coord>....
`

With this data structure (without spaces before `<geom:coord>`)  the validator logs the error: "unexpected start element coord":

`<Revitalisierung_Seen_V2:Uferlinie_Geometrie ili:tid="22"><Revitalisierung_Seen_V2:UferTeilstueck><geom:polyline><geom:coord><geom:c1>2716790.5120285717</geom:c1><geom:c2>1226221.6561714285</geom:c2></geom:coord><geom:coord><geom:c1>2716791.177</geom:c1><geom:c2>1226221.038</geom:c2></geom:coord><geom:coord><geom:c1>2716792.668666667</geom:c1><geom:c2>1226219.055857143</geom:c2></geom:coord></geom:polyline>......`

Is this on purpose? Am I overseeing something?

Kind regards
[Revitalisierung_Seen_V2.log](https://github.com/claeis/ilivalidator/files/6334587/Revitalisierung_Seen_V2.log)
[Revitalisierung_Seen_V2_bug.log](https://github.com/claeis/ilivalidator/files/6334588/Revitalisierung_Seen_V2_bug.log)

**Comment by beistehen** [comment]
> Am I overseeing something?

Hard to tell from the log file because there is no line indicated where the error occurs. Can you

- provide the ili2.4-data and/or
- run ilivalidator with the `--trace` option and post the log file?

**Comment by threalslimtobeeee** [comment]
Here you go.

I am not able to upload the data.  I will send it to you via email.

[Revitalisierung_Seen_V2_bug2.log](https://github.com/claeis/ilivalidator/files/6340942/Revitalisierung_Seen_V2_bug2.log)

**Comment by beistehen** [comment]
I could reproduce the behaviour in the test environment. This is a bug. And a quick test shows that INTERLIS 2.3 is affected as well.
Thanks for sharing!

**Comment by claeis** [comment]
will fix it
