### ISSUE TITLE
Nested-shells are not detected

### ISSUE THREAD

**Issue by pasimo** [claeis/ilivalidator#307]
By mistake we splitted and aggregated some donut polygons to multipolygons. The donut holes are now polygons itsself, but nested within the outer shell. These nested-shells are not [allowed ](https://community.safe.com/s/article/invalid-ogc-geometry-examples) and therefore ilivalidator should be able to detect them.

[ilivalidator_nested_shells_detection.zip](https://github.com/claeis/ilivalidator/files/6399744/ilivalidator_nested_shells_detection.zip)

**Comment by claeis** [comment]
As the model is, this is valid data::

    CLASS PlanningMeasure =

      Surface : GeometryCHLV03_V1.MultiSurface;

    END PlanningMeasure;

There is no constraint, that the surfaces should not overlap per PlanningMeasure.
