### ISSUE TITLE
Speed of AREA-Constraint vs areAreas() vs switched off object cache

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#308]
Ich habe für die Teileinzugsgebiete der Stadt Bern (circa 15'000 Objekte, mehr oder weniger den Liegenschaften entsprechend) einen areArea-Constraint definiert. Die Prüfung habe ich unvollendet nach einer Stunde abgebrochen.

Gemäss Logoutput ist der object cache ausgeschaltet: `Info: flushWriteQueues(): switch off object cache (ObjectPoolManager.java:73)`

Mit einem kleineren Datensatz (Grundnutzung Olten) habe ich die Geschwindigkeit zwischen einem "normalen" Area-Constraint, d.h. die Geometrie ist als AREA definiert und einem areAreas()-Constraint, d.h. Geometrie ist als SURFACE definiert. Die "normale" AREA-Bedingung wird circa 15 Sekunden schneller geprüft (90s vs 75s).

- Ist der ausgeschaltete Objektcache für die Performance ausschlaggebend?
- Warum ist areAreas() langsamer als eine "normale" AREA-Bedingung?

<img width="1386" alt="Screenshot 2021-04-30 at 17 20 16" src="https://user-images.githubusercontent.com/2767800/116719186-1169a400-a9db-11eb-92ba-0d51a5d0efb2.png">

**Comment by edigonzales** [comment]
Das schlecht Skalierende und der Unterschied zur "normalen" AREA-Bedingung ist wohl die while-Schleife: https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1189

Und der Methodenaufruf von "evaluateExpression()": https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1205

**Comment by Philippluca** [comment]
@claeis Ich werde hierfür mal eine Analyse fahren.

**Comment by Philippluca** [comment]
Ich habe nun einige neue Einsichten gewonnen. Der Unterschied in der Ausführungszeit von 20% und mehr konnte ich in meinem Testbeispiel ebenfalls beobachten, bei gleichen Einstellungen. Also in beiden Fällen keine `switch off object cache` Meldung.

Für den Fall `AREA` werden die Geometrien bereits im ersten durchgang für die Validierung zusammengetragen. Dies passiert bei `Validator.validateObject() -> validateAttrValue()` [L#3666](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/Validator.java#L3666). Im `doSecondPass() -> validateAllAreas()` wird die eigentliche Validierung durchgeführt, welche bereits sehr optimiert funktioniert.

Für den Fall `INTERLIS.areArea(_,_,_)` werden im ersten Pass [alle SetConstraints gesammmelt](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/Validator.java#L438). Dies ist eine günstige angelegenheit. In `doSecondPass -> iterateThroughAllObjects()` werden alle Objekte welche die Precondition erfüllen gesammelt ([collectSetConstraintObj()](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1103)). Als letzte Aktion von `iterateThroughAllObjects()` wird für alle SetConstraints einmal [validateSetConstraint(constraint))](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1157) aufgerufen. Innerhalb dieser Methode wird [`evaluateExpression()`](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1205) für jedes Objekt nochmals aufgerufen. Im falle von `INTERLIS.areArea` zwar nicht notwendig, jedoch bei anderen Constraints allenfalls schon. Bis hier hin sehe ich kein Problem, welches grosse Performance einbussen auslösen könnte.

Der Aufruf landet dann bei der [Impelementation von areArea() in Interlis.java](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/functions/Interlis.java#L228). Hier konnte ich mit dem JDK Mission Control einen grossen Teil der Arbeit validator.evaluateExpression bzw. dem ObjectPool zuordnen. Ich vermute, dass diese Last durch die evaluierung der Variabeln `argObjects`, `argSurfaceBag`, `argSurfaceAttr` verursacht werden. 

![image](https://user-images.githubusercontent.com/2191817/129855061-7d21ce5a-9986-4eb4-a823-408e2aac4471.png)


Diese werden bei jedem Aufruf neu evaluiert (also für jedes Objekt). Während dieser Aufrufe kann ich eine grosse Last auf mein Drive beobachten (mit 20 MB/s genug um das File jede Sekunde zu laden). Am [Ende der Methode](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/functions/Interlis.java#L305) wird noch überprüft, ob es bereits ein Resultat für `currentFunction` gibt. Das könnte eventuell vor den erwähnten evaluierungen geschehen, ich bin jedoch nicht sicher, ob wir dann notwendige Evaluierungsschritte verlieren. @claeis was meinst du dazu?

[TestData.zip](https://github.com/claeis/ilivalidator/files/7005308/TestData.zip)

**Comment by Philippluca** [comment]
Nachdem wir nun unsere eigene Funktionsbibliothek entwickelt haben, steht für uns klar: Die Performance von `areArea` kann durch die korrekte Anwendung vom Caching mit `currentFunction` kann die Performance stark gesteigert werden. Die [Prüfung auf ein gecachtes Resultat](https://github.com/claeis/iox-ili/blob/6b9d1fb0bd3ef13de401a8d37c23d09a80e79125/src/main/java/ch/interlis/iox_j/validator/functions/Interlis.java#L305) muss vor der Evaluierung der Parameter geschehen.

**Comment by edigonzales** [comment]
@Philippluca Kannst du abschätzen resp. weisst du, ob "stark gesteigert" bedeutet, dass es gleich schnell wird wie die "normale " Area-Prüfung oder das aus Gründen gar nie möglich sein kann (weil z.B. immer mehr gemacht werden muss, weil es eben ein SET CONSTRAINT ist).

**Comment by Philippluca** [comment]
@edigonzales Ich erwarte, dass wir sehr nahe an die Performance von AREA Bedingungen kommen werden. Ganz gleich schnell wird es nicht werden, da bei einem SET CONSTRAINT die betroffenen Objekte in einer eigenen Routine evaluiert werden müssen. Momentan beläuft sich diese Evaluierung auf n*n. Mit einer Anpassung auf 1*n.

**Comment by claeis** [comment]
requires claeis/iox-ili#107
