### ISSUE TITLE
arc converted to straight: error and warning

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#31]
In some cases "arc converted to straight" is shown as error since 0.10.0. If on purpose, why?

`Info: validate unique constraint DM01AVCH24LV95D.FixpunkteKategorie3.LFP3Symbol.Constraint1...`
`Info: validate unique constraint DM01AVCH24LV95D.Bodenbedeckung.BBNachfuehrung.Constraint1...`
`Warning: arc converted to straight at tid 68033978, (2610782.617, 1230308.023, NaN)`
`Warning: arc converted to straight at tid 68028526, (2611669.616, 1229329.356, NaN)`
`Warning: arc converted to straight at tid 68034205, (2611671.385, 1229888.676, NaN)`
`Warning: arc converted to straight at tid 68034204, (2611669.715, 1229888.608, NaN)`
`Warning: arc converted to straight at tid 68032257, (2611111.983, 1229720.288, NaN)`
`Info: validate unique constraint DM01AVCH24LV95D.Einzelobjekte.EONachfuehrung.Constraint1...`
`Error: line 137027: DM01AVCH24LV95D.Einzelobjekte.Linienelement: tid 73000586: arc convertet to straight at (2611225.696, 1229749.459, NaN)`
`Error: line 137658: DM01AVCH24LV95D.Einzelobjekte.Linienelement: tid 73000684: arc convertet to straight at (2611823.931, 1229867.722, NaN)`
`Info: validate unique constraint DM01AVCH24LV95D.Nomenklatur.NKNachfuehrung.Constraint1...`
`Info: validate unique constraint DM01AVCH24LV95D.Liegenschaften.LSNachfuehrung.Constraint1...`

**Comment by edigonzales** [comment]
e.g. [https://data.geo.admin.ch/ch.swisstopo-vd.amtliche-vermessung/DM01AVCH24D/ITF/SO/2523.zip](url)

**Comment by claeis** [comment]
Should be an error and not a warning (reporting that there is an degenerated ARC in the transfer that is really a straight line)

**Comment by edigonzales** [comment]
There is a typo: convertet -> converted.

**Comment by edigonzales** [comment]
Up which tolerance an arc is still accepted or is converted to a line (with an warning) and when is an arc degenerated?

**Comment by claeis** [comment]
reported always as warning in 1.0.0 (because it was tolerated practice in the past and would make to many datasets invalid)
