### ISSUE TITLE
The name of the model conflicts with MODEL; topic hazard_mapping

### ISSUE THREAD

**Issue by kglaus** [claeis/ilivalidator#310]
Hello there

I try to implement only the lv95 version for the topic Gefahrenkarten v1.3 for which i use ili2pg 4.5.0 and ilivalidator 1.11.10. 
I can create the DB scheme based on the lv95.ili without a problem. As soon as i try to import some testdata the following error occurs:

_Error: /home/rails/.ilicache/models.geo.admin.ch/BAFU/Hazard_Mapping_V1_3.ili:48:The name of the model conflicts with MODEL Hazard_Mapping_LV95_V1_3. Model names must be unique; please use a different name.
Error: compiler failed_ (see also:  [logfile_error.txt](https://github.com/claeis/ilivalidator/files/6521637/logfile_error.txt))

When I prepare the setup with the 03.ili as well as the lv95.ili, the DB scheme is created without a problem. The import with the testdata also works but now takes 2 1/2 hours. Which seems also suspicious.

Is it not possible to create a topic just for lv95 if there is an exisisting lv03.ili in the models.geo.admin.ch repository?

ili-files:
[hazard_mapping_LV03_V1_3.txt](https://github.com/claeis/ilivalidator/files/6521513/hazard_mapping_LV03_V1_3.txt)
[hazard_mapping_LV95_V1_3.txt](https://github.com/claeis/ilivalidator/files/6521514/hazard_mapping_LV95_V1_3.txt)

**Comment by edigonzales** [comment]
What are the exact commands? Can you share the data?

**Comment by kglaus** [comment]
The command is the following curl command: 
_curl -u *:* -F topic=gefahrenkarten_v1_3 -F lv95_file=@/home/kglaus/Fileupload/sh_hazard_mapping_lv95_v1_3_20210301.zip -F canton=SH -F publish=true -F replace_all=true "https://dev2.geodienste.ch/data_agg/interlis/import"_ 
with schemaimport option  _--models 'Hazard_Mapping_LV95_V1_3'_ and ilivalidator option _--forceTypeValidation_

Testdata: https://dev2.geodienste.ch/downloads/interlis/gefahrenkarten/SH/gefahrenkarten_v1_3_SH_lv95.zip

**Comment by edigonzales** [comment]
I knew I saw the error before: https://github.com/claeis/ili2c/issues/55

**Comment by edigonzales** [comment]
Was ich beim Schemaimport-Befehl nicht ganz durchschaue: Warum --defaultSrsCode 21781 aber Modellfile LV95?

Works for me (ili2pg v4.3.1) mit deinem ili-file. Dauer 2m 17s:

```
java -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg-4.3.1.jar \
--dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin \
--dbschema gefahrenkarten_v1_3 --schemaimport \
--createGeomIdx --defaultSrsCode 2056 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807 --oneGeomPerTable --createEnumTxtCol --disableValidation /Users/stefan/Downloads/hazard_mapping_LV95_V1_3.ili

java -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg-4.3.1.jar \
--dbschema gefahrenkarten_v1_3 --models Hazard_Mapping_LV95_V1_3 \
--dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin \
--defaultSrsCode 2056 --disableValidation \
--dataset SH --replace gefahrenkarten_v1_3_SH_lv95/sh_hazard_mapping_lv95_v1_3_20210129.xtf
```

**Comment by dkottmann** [comment]
Auszug aus HEADERSECTION des bereitgestellten xtf: 

`<HEADERSECTION SENDER="ili2pg-4.4.4-5586f5e20f4e40fd05286ecb363ec6d450b85cfa" VERSION="2.3"><MODELS><MODEL NAME="CoordSys" VERSION="2015-11-24" URI="http://www.interlis.ch/models"></MODEL><MODEL NAME="Units" VERSION="2012-02-20" URI="http://www.interlis.ch/models"></MODEL><MODEL NAME="GeometryCHLV03_V1" VERSION="2017-12-04" URI="http://www.geo.admin.ch"></MODEL><MODEL NAME="GeometryCHLV95_V1" VERSION="2017-12-04" URI="http://www.geo.admin.ch"></MODEL><MODEL NAME="Hazard_Mapping_LV95_V1_3" VERSION="2020-12-01" URI="https://models.geo.admin.ch/BAFU/"></MODEL><MODEL NAME="Hazard_Mapping_LV03_V1_3" VERSION="2020-12-01" URI="https://models.geo.admin.ch/BAFU/"></MODEL></MODELS></HEADERSECTION>
`

Da werden offenbar LV03 Modelle referenziert. Muss das so sein? Aus meiner Sicht logisch, dass das nicht funktionieren kann, da diese LV03-Modelle beim Schemaimport nicht benutzt wurden...?

**Comment by dkottmann** [comment]
Ach so, der Compiler Fehler kommt beim ilivalidator. Trotzdem: Ist es legitim, dass in der HEADERSECTION eines XTF sowohl die LV95 als auch die LV03 Variante vorkommt?

**Comment by kglaus** [comment]
Vielen Dank für die Inputs und Hilfe.
Das Problem hat sich gelöst, indem ich die LV03 Versionen aus dem Header des xtf entfernt hatte.

**Comment by beistehen** [comment]
> Ist es legitim, dass in der HEADERSECTION eines XTF sowohl die LV95 als auch die LV03 Variante vorkommt?

Legitim (gemäss RefHB) wohl schon, aber ungünstig. Siehe auch #287 . Dieses Issue trat auf beim FME-Export mittels ili2fme.
