### ISSUE TITLE
Custom functions with BAG OF STRUCTURES

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#32]
I tried something like this in the ili-file:

`FUNCTION foobar (bag: BAG OF ANYSTRUCTURE): BOOLEAN;`

`CLASS Liegenschaft(EXTENDED) =`
`     Korrektur : GB2AV.FlaechenKorrektur;`
`      korrigiertesFlaechenmass : GB2AV.Flaeche;`
`      Zugang : BAG {0..*} OF Abschnitt;`
`      MANDATORY CONSTRAINT foobar(Zugang);`
`    END Liegenschaft;`

In my evaluate() method of the custom function I _think_ I only receive one structure:

`Value[] args = getActualArguments();`
`Value val = (Value) args[0];`

`val.getComplexValue()` returns one structure.
`val.getValues()` returns null.

[Archive.zip](https://github.com/claeis/ilivalidator/files/783218/Archive.zip)

**Comment by claeis** [comment]
fixed in 1.0.0
