### ISSUE TITLE
Correctly test uniqueness of TIDs across the whole file

### ISSUE THREAD

**Issue by andreasneumann** [claeis/ilivalidator#320]
In the attached XTF file, the following two TIDs are used twice:

d7f86429-dd7c-44f9-ae46-408163572ae7
f860798f-8169-44c8-a896-7eecdca96ebe

They are used in two different baskets: SO_Nutzungsplanung_20171118.Nutzungsplanung and SO_Nutzungsplanung_20171118.Erschliessungsplanung

ilivalidator should throw an error if the uniqueness of a TID is violated.

**Comment by andreasneumann** [comment]
[2545.zip](https://github.com/claeis/ilivalidator/files/7185761/2545.zip)

The sample file containing the error.

**Comment by beistehen** [comment]
As the reference manual states in chapter 1.4.5:
> Als Behälter wird eine abgeschlossene Sammlung von Objekten bezeichnet, die zu einem Thema oder zu
> dessen Erweiterungen gehören. Abgeschlossen heisst, dass ein Behälter alle Objekte enthalten soll, die
> innerhalb des Themas zueinander in Beziehung stehen. Typischerweise wird ein Behälter alle Objekte
> einer bestimmten Gegend (z.B. einer Gemeinde, eines Kantons oder gar des ganzen Landes) enthalten.

I would consider the whole dataset (file) as one transfer and therefore put all the data in the same basket. When you do this, ilivalidator throws the aforementioned error as expected.
