### ISSUE TITLE
Cannot copy xtf path to log path anymore

### ISSUE THREAD

**Issue by sjib** [claeis/ilivalidator#321]
With the new ilivalidator 1.11.11 I cannot copy anymore the xtf path (Datei-Pfad) on Windows with Ctrl-C to the log path (Log-Datei) (paste Ctrl-V). This was very helpful to easily add a log in the same directory by then adding *.log at the end.

Why is this blocked now?

![ilivalidator1 11 11_dateipfad](https://user-images.githubusercontent.com/1265865/135237793-f1250caf-2324-4f87-babc-cb2a278f9b8b.jpg)

When I choose ... to select a log file, I cannot select the xtf as it warns me to not overwrite it (that's ok to prevent this). 

Usually I do not have a log file I can choose from as I want it created.

But I need now to first get the directory path from the File manager, I can copy it and then I have to add it manually and the add the full file name - so this is a lot of hassle as user.

**Comment by beistehen** [comment]
When doing GUI improvements (which would for sure enhance the overall user experience), please also consider the following issues:
#259 #264 #267 #268 

Maybe something for @patrickackermann or @Philippluca ?

**Comment by sjib** [comment]
Thanks for solving - works again as expected and before 1.11.11 in the new 1.11.12. vom 10.11.2021
