### ISSUE TITLE
Validation stalls when polygon is empty

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#322]
Empty Polygon = `<SURFACE></SURFACE>`

Beispieldatensatz: Sieht TID=121949
[Archive.zip](https://github.com/claeis/ilivalidator/files/7304206/Archive.zip)

**Comment by claeis** [comment]
- iox-ili:Xtf23Reader inkl. Tests fertigstellen und in iox-ili:ReaderFactory usw. einbinden 
- nicht ch.interlis.iom_j.xtf.impl.MyHandler korrgieren!

**Comment by edigonzales** [comment]
`java -jar ilivalidator.jar fubar.xtf`

**Comment by claeis** [comment]
Tests müssen Kap 3 des INTERLIS Referenzhandbuchs abdecken. Bestehende Tests sind Xtf23ReaderTest, Xtf23ReaderHeaderTest, Xtf23ReaderDataTest, Xtf23ReaderAssociationTest

**Comment by claeis** [comment]
fixed in c3b99887c693ae449ff85d0af94ecb6f736efa59
