### ISSUE TITLE
Validate VIEW in non-validation models

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#324]
Falls im Datenmodell (der zu prüfenden Daten) eine View definiert ist mit zusätzlichen Constraints, werden diese nicht validiert.

**Comment by edigonzales** [comment]
Ilivalidator wertet die Constraints in der View `v_Dokument` nicht aus (siehe Anhang), wenn die View innerhalt des Originalmodelles definiert ist. Es muss zwingend ein separates Modell erstellt werden. 

Erwartung: View-Definitionen (im Originalmodell) mit ihren zusätzlichen Constraints werden von ilivaliadator ausgewertet identisch der Definition von Views und Constraints in Zusatzmodellen.

[SO_Nutzungsplanung_20171118.ili.zip](https://github.com/claeis/ilivalidator/files/7894752/SO_Nutzungsplanung_20171118.ili.zip)
.

**Comment by claeis** [comment]
s.a. #127, #128

**Comment by claeis** [comment]
Dieses Issue umfasst nur ViewDef im Umfang wie sie schon implementiert sind (also ohne #127 und #128)

**Comment by claeis** [comment]
ValidatorTest.xtfFailWithAdditionalModel() ist ein Beisipiel-Test mit einem Zusatzmodell.

**Comment by edigonzales** [comment]
Im Validierungsmodell `SO_Nutzungsplanung_20171118_Validierung_20211006.ili` ist eine View mit zusätzlichen Constraints definiert. Diese prüfen z.B. ob das Attribut `Rechtsvorschrift` vorhanden ist:

```
java -jar ilivalidator.jar --config config.toml 2457.xtf
```

Ilivalidator findet einen Fehler (siehe Logoutput).

Wenn man diese View im Originalmodell definiert, findet ilivalidator den Fehler nicht:

```
java -jar ilivalidator.jar 2457.xtf
```

Der Fehler sollte bereits entdeckt werden, wenn die View im Originalmodell definiert ist.
[Archive.zip](https://github.com/claeis/ilivalidator/files/7939674/Archive.zip)

**Comment by olivergrimm** [comment]
Wir haben dasselbe Problem nachvollziehen können in einem anderen Projekt / Modell.

**Comment by olivergrimm** [comment]
Die Umsetzung dieses Issues wurde gesponsert vom Kanton Solothurn
