### ISSUE TITLE
Evaluate each element of list/bag

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#33]
It would be nice if there is the possibility to set a constraint for each element of a list/bag.

**Comment by claeis** [comment]
Please provide an example of what is expected

**Comment by edigonzales** [comment]
`STRUCTURE Abschnitt =`
`   Flaechenmass : MANDATORY GB2AV.Flaeche;`
`   von : MANDATORY GB2AV.GrundstueckNummer;`
`END Abschnitt;`

`CLASS Liegenschaft(EXTENDED) =`
`   Korrektur : GB2AV.FlaechenKorrektur;`
`   korrigiertesFlaechenmass : GB2AV.Flaeche;`
`   Zugang : BAG {0..*} OF Abschnitt;`
`   MANDATORY CONSTRAINT isInteger(Zugang->Flaechenmass);`
`END Liegenschaft;`

Constraint `isInteger` should check that `Flaechenmass` has no decimal place (=xxx.0).

**Comment by claeis** [comment]
The current ili-language would require a VIEW. 
Possible workaround: `MANDATORY CONSTRAINT isInteger("Zugang->Flaechenmass");`
