### ISSUE TITLE
Definition of the OID - different interpretation?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#333]
There are OIDs like this

```
ch1584qrIw0mf~Sl
ch1584qrIw0nFMl^

```
ilivalidator reports "value <ch1584qrIw0nFMl^> is not a valid OID", based on the (here often discussed) "Interlis Reference 3.3.1, { Letter | Digit | '_' | '-' | '.' }"

Other validators accept these OIDs, maybe based on  "Interlis Reference, Anhang D, Postfix: Sequenz (numerisch oder alphanume-
risch) des Produzentensystems als 'lokaler' Identifikations-Anteil". And "alphanumeric" can be understood not only as "a-z, 0-9" but also incl special chars, diacritics an so on: see https://de.wikipedia.org/wiki/Alphanumerische_Zeichen 

I'm confused - is there a "common and absolute correct" definition?
Or are there really different interpretations?

**Comment by claeis** [comment]
Interlis Reference 2.8.9 (references [XML](http://www.w3.org/TR/REC-xml)) and 3.3.11.16 (references XML-ID: 3.3.1).

In your example ```~``` and ```^``` are the invalid charcaters.

**Comment by Pierre-de-la-Verre** [comment]
Thanks.
