### ISSUE TITLE
`Error:   No space left on device` Auslagerungsdateien

### ISSUE THREAD

**Issue by kglaus** [claeis/ilivalidator#335]
Beim validieren von Daten auf geodienste.ch mit dem ilivalidator 1.11.10 gab es für die Gefahrenkarten v1.3 den folgenden Fehler: 
`Error: java.io.IOException: No space left on device`
`Error:   No space left on device`

Dasselbe xtf mit der ilivalidator 1.11.3 kann validiert werden.

Es scheint immer noch Diskrepanzen mit den Auslagerungsdateien in den verschiedene Ilivalidatorversionen zu geben.
@claeis Weisst du woran das liegt? Könntest du in zukünftigen Versionen diese Diskrepanzen ausmerzen oder diesen auf den Grund gehen?

[logfile_erfolgreich.txt](https://github.com/claeis/ilivalidator/files/7641746/logfile_erfolgreich.txt)
[logfile_error.txt](https://github.com/claeis/ilivalidator/files/7641945/logfile_error.txt)

**Comment by beistehen** [comment]
Die Logfiles sprechen aber von anderen ilivalidator-Versionen:

- erfolgreich: `ilivalidator-1.11.3`
- error: `ilivalidator-1.8.1`

Zur bemängelten Version 1.11.10 gibts kein Log... 🧐

**Comment by kglaus** [comment]
Vielen Dank für die Rückmeldung. Jetzt sollte das richtige Logfile da sein.

**Comment by edigonzales** [comment]
Ist sicher was für @claeis. Aber ist es der gleiche Server? Wurde das tmp-Verzeichnis zwischenzeitlich gelöscht?

**Comment by kglaus** [comment]
Der Job-Server wird für jeden Import neu geklont. Das tmp-Verzeichnis ist somit für jeden Import "leer".

**Comment by claeis** [comment]
Also wenn es auf der Platte keinen Platz mehr hat, hat es keinen Platz mehr. Was soll ich genau machen?

**Comment by edigonzales** [comment]
So wie ich es verstehe, funktioniert es unter den identischen Plattenplatzvoraussetzungen mit einer bestimmten ilivalidator-Version. Mit einer neueren nicht mehr.

**Comment by beistehen** [comment]
> Falls am Code diesbezüglich nichts geändert wurde, sind wohl die Bedingungen doch nicht ganz gleich.

Hilfreich wäre, wenn man die fehlerhafte Validierung nachstellen könnte, also mit .ili aus dem Repo, .xtf und config.toml...

**Comment by claeis** [comment]
Es ist normal, dass die verschiedenen Versionen nicht gleich viel Platz auf dem Disk benötigen.
  - mehr Platz wird benötigt, wenn mehr Zwischenresultate ausgelagert werden (um RAM zu sparen; um gössere Datein mit weniger RAM prüfen zu können)
  - weniger Platz wird benötigt, wenn am Auslagerungsmechanismus etwas verbessert wird

Beides kommt vor.

**Comment by kglaus** [comment]
Ich denke das Ticket kann geschlossen werden.

**Comment by kglaus** [comment]
Ich habe einmal die Speicherauslastung meines Clients geloggt, währen die Ilivalidator Versionen 1.11.12 sowie 1.11.3 mit einem Gefahrenkartenfile durchgelaufen sind.
Die Unterschiede in der Speicherauslastung sind schon sehr gross:

[Vergleich_ilivalidator.txt](https://github.com/claeis/ilivalidator/files/7727428/Vergleich_ilivalidator.txt)

Die Auslagerungsdatei für 1.11.12 ist doppelt so gross wie für 1.11.3. Zu bemerken ist noch, dass das Testfile nur circa 1/4 der originalen Daten enthielt.

Zusatzfragen:
Ist es möglich die Auslagerungsdatei in einen S3-Bucket zu schreiben? Falls nein, wäre so etwas sinnvoll und machbar?

**Comment by claeis** [comment]
Bitte mit aktuellem [SNAPSHOT](https://jars.interlis.ch/ch/interlis/ilivalidator/1.11.15-SNAPSHOT/ilivalidator-1.11.15-20220620.144737-3-bindist.zip) laufen lassen (inkl. --trace). Im Log sollte dann stehen, wie gross die Auslagerungsdateien sind.

**Comment by claeis** [comment]
Problem scheint die Auslagerung der Beziehungen zu sein:

    XTF file: size 10'026'240'112
    ObjectPool: size 5'558'285'650
    LinkPool KEY: size 16'557'892'252
    LinkPool VAL: size 300'844'584

**Comment by claeis** [comment]
Ich kann es nicht reproduzieren. Bei mir dauert die vollständige Validierung gut 3min.

Mit --trace erhält man am Ende der Validierung auch die Dateigrössen der Auslagerungsdateien:

     Info: close(): LinkPool KEY: size 522, filesize 303529
     Info: close(): LinkPool VAL: size 6264
     Info: close(): CompoundCurveNoder KEY: size 363647, filesize 1417204
     Info: close(): CompoundCurveNoder VAL: size 2294485320
     Info: close(): ObjectPool: size 2235942
     Info: close(): ObjectPool: size 508
     Info: close(): ItfAreaPolygon2Linetable: size 1969252
     Info: close(): CompoundCurveNoder: size 0

M.E. auch nicht wirklich dramatisch, ausser vielleicht "CompoundCurveNoder VAL: size 2294485320" (=Auslagerungsdatei für die Geometrien bei der AREA-Prüfung)

Das kann man somit reduzieren, indem man die Prüfung des SET CONSTRAINT bei der Klasse Laermempfindlichkeit_Zonenflaeche ausschaltet. Also ein Konfig-File mit:

     [Laermempfindlichkeitsstufen_V1_2.Geobasisdaten.Laermempfindlichkeit_Zonenflaeche.Constraint1]
     check=off


Dann dauert die Validierung noch 20 sek. Und

     Info: close(): LinkPool KEY: size 522, filesize 303529
     Info: close(): LinkPool VAL: size 6264
     Info: close(): ObjectPool: size 2235942
     Info: close(): ObjectPool: size 508
