### ISSUE TITLE
Add statistics to log file

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#34]
It would be nice to have a statistics section at the end of the log file like igCheck, eg.

**2300 objects in class A**
**3411 objects in class B**
**...**

**14 model constraints violated: attribute 'Art' is MANDATORY**
**23 meta constraints violated: attribute 'LFPNummer' is more than 16 characters**
 **2 toml constraints suppressed warnings for mandatory references**
**...**

**Comment by ltzur** [comment]
KOGIS unterstützt dieses Anliegen, gerade bei Prüfungen vor und nach der Datenlieferung ist eine solche Statistik äusserst hilfreich.

**Comment by claeis** [comment]
1.6.0
