### ISSUE TITLE
areAreas validation broken (?)

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#342]
```
    CLASS Bauzonengrenze =
      Zonentyp : MANDATORY (
        Reservezone,
        Bauzone
      );
      Geometrie : MANDATORY GeometryCHLV95_V1.MultiSurface;
      BFSNr : MANDATORY 0 .. 9999;
      SET CONSTRAINT INTERLIS.areAreas(ALL, UNDEFINED, >> Geometrie);
    END Bauzonengrenze;
```

Daten: [ch.so.arp.bauzonengrenzen.xtf.zip](https://github.com/claeis/ilivalidator/files/8824885/ch.so.arp.bauzonengrenzen.xtf.zip)

Modell: https://geo.so.ch/models/ARP/SO_ARP_Bauzonengrenzen_20210120.ili

Mit 1.11.13 funktionierts. @patrickackermann hat das was mit den Arbeiten an areAreas in iox-ili zu tun?

**Comment by claeis** [comment]
Das Modell ist falsch. Richtig wäre:

    SET CONSTRAINT INTERLIS_ext.areAreas3(ALL, UNDEFINED, "Geometrie->Surfaces->Surface");

**Comment by edigonzales** [comment]
Merci. Dann rechnet es bei mir jetzt "endless" für die Daten im Ticket. Und ich glaube es füllt relativ rasch die Festplatte.


Output: 
```
Error: SO_ARP_Bauzonengrenzen_20210120.Bauzonengrenzen.Bauzonengrenze: tid 45469/Geometrie[1]/Surfaces[2]/Surface[1]: Intersection coord1 (2605215.353, 1229441.734), tids 45460/Geometrie[1]/Surfaces[1]/Surface[1], 45469/Geometrie[1]/Surfaces[2]/Surface[1]
Error: SO_ARP_Bauzonengrenzen_20210120.Bauzonengrenzen.Bauzonengrenze: tid 45469/Geometrie[1]/Surfaces[2]/Surface[1]: Intersection coord1 (2605215.222, 1229442.447), tids 45460/Geometrie[1]/Surfaces[1]/Surface[1], 45469/Geometrie[1]/Surfaces[2]/Surface[1]
Error: SO_ARP_Bauzonengrenzen_20210120.Bauzonengrenzen.Bauzonengrenze: tid 45469/Geometrie[1]/Surfaces[2]/Surface[1]: Intersection coord1 (2605215.176, 1229442.827), tids 45460/Geometrie[1]/Surfaces[1]/Surface[1], 45469/Geometrie[1]/Surfaces[2]/Surface[1]
```

**Comment by edigonzales** [comment]
Mit 1.11.13 wird die Validierung beendet ("validation failed"). Die Fehler werden gemeldet. **Dünkt** mich schneller als 1.11.14 (bis zum Einfrieren).

**Comment by edigonzales** [comment]
Kann man `INTERLIS_ext` im UML-Editor importieren?

**Comment by olivergrimm** [comment]
@edigonzales Wir haben einen Testrun mit Deinen Daten und mit dem in [https://github.com/claeis/iox-ili/pull/108](https://github.com/claeis/iox-ili/pull/108) gemergten Patch durchgeführt. Da ist die Validierung in 1m41s durch (in IntelliJ). Im aktuellen Release 1.11.14 arbeitet die Validierung bereits grundsätzlich korrekt, aber halt noch ohne Cache bei 'ALL')

**Comment by claeis** [comment]
> Kann man `INTERLIS_ext` im UML-Editor importieren?

Ja, ab claeis/ili2c@15a7ae1324d29f86702e594c24fc17d97206c1ca
