### ISSUE TITLE
--allObjectsAccessible in config file not working

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#350]
```
["PARAMETER"]
allObjectsAccessible="true"
```

Mit/ohne Anführungszeichen oder "on" funktioniert nicht.

**Comment by claeis** [comment]
allObjectsAccessible=ValidationConfig.TRUE.equals(validationConfig.getConfigValue(ValidationConfig.PARAMETER, ValidationConfig.ALL_OBJECTS_ACCESSIBLE));
