### ISSUE TITLE
Crossvalidation check issue

### ISSUE THREAD

**Issue by leader80** [claeis/ilivalidator#36]
We are still experiencing the crossvalidation problem, please find attached the example

[2 - Schutzbauten_V05_zweite_Anhörung.ili.txt](https://github.com/claeis/ilivalidator/files/828172/2.-.Schutzbauten_V05_zweite_Anhorung.ili.txt)
[export_ch.xtf.txt](https://github.com/claeis/ilivalidator/files/828171/export_ch.xtf.txt)

[https://github.com/claeis/ilivalidator/issues/27](url)

thanks
G.

**Comment by claeis** [comment]
Which constraint violation is not reported?

**Comment by leader80** [comment]
Are reported several issues but there aren't any.

**Comment by claeis** [comment]
Please, be more specific.

**Comment by leader80** [comment]
igcheck:

============================================================================================================
checking basket Schutzbauten_LV03_V05.Schutzbauten bid=Schutzbauten_LV03_V05.Schutzbauten ...
============================================================================================================
*** ERROR *** CHECK(errid=70) UNIQUE constraint Schutzbauten_ID (values=RM011) violated, see also line 6
              LINE=7,TOPIC=Schutzbauten,CLASS=Schutzbautenobjekt,TID=78
*** ERROR *** CHECK(errid=70) UNIQUE constraint Schutzbauten_ID (values=RM011) violated, see also line 6
              LINE=13,TOPIC=Schutzbauten,CLASS=Schutzbautenobjekt,TID=82
*** ERROR *** CHECK(errid=60) MANDATORY constraint CONSTRAINT_Schutzbauten_LV03_V05_5 failed for object Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt
              LINE=14,TOPIC=Schutzbauten,CLASS=Schutzbautenobjekt,TID=11

ilivalidator:

Info: validate data...
Info: first validation pass...
Info: validate unique constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint1...
Info: second validation pass...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint2...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint3...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4...
Error: line 20: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 105: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint5...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint6...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint7...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint8...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint9...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint10...
Info: validate mandatory constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint11...
Info: validate role references of Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt...
Error: line 19: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 103: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint7 is not true.
Error: line 18: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 101: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 17: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 100: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 7: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 78: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 6: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 79: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 15: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 98: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 14: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 11: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint2 is not true.
Error: line 14: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 11: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 16: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 99: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 21: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 88: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint6 is not true.
Error: line 8: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 96: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 9: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 74: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 10: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 97: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 11: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 75: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 5: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 73: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 23: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 109: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint5 is not true.
Error: line 13: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 82: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Error: line 22: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 108: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint7 is not true.
Error: line 12: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 80: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint4 is not true.
Info: ...validation failed
Please find attached the logs:
[output_validator.txt](https://github.com/claeis/ilivalidator/files/831621/output_validator.txt)
[output_ig_check.txt](https://github.com/claeis/ilivalidator/files/831623/output_ig_check.txt)

Thanks
G

**Comment by claeis** [comment]
fixed in 1.0.0

**Comment by giodegiorgi** [comment]
Lovely! Thanks!

Really appreciated!
