### ISSUE TITLE
A TRANSLATION OF model must not define new types, but only an alternative transfer format

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#361]
Obwohl im FR Modell der Nutzungsplanung steht:
    ASSOCIATION TypeCt_CatalogueCH =
      Type_Ct -- {0..*} Type_Ct;
      Catalogue_CH (EXTERNAL) -- {1} PlansDAffectation_V1_2.Catalogue_CH.Catalogue_CH;
    END TypeCt_CatalogueCH;

Und entsprechend in der Transferdatei das Objekt mit FR Tags codiert ist:

      <PlansDAffectation_V1_2.GeodonneesDeBase.Type_Ct TID="04053910-cc82-45fe-ba2d-dc20144f9cc0">
        <Code>12</Code>
        <Designation>Zone industrielle et artisanale</Designation>
        <Abreviation>IA</Abreviation>
        <Catalogue_CH REF="ch.admin.are.nutzungsplanung_catalogue_ch.12"></Catalogue_CH>
      </PlansDAffectation_V1_2.GeodonneesDeBase.Type_Ct>

Ist der Verweis auf das mit DE Tags codierte Objekt des dazugehörenden Katalogs ch.admin.are.nutzungsplanung_catalogue_ch.12 korrekt 

      <Nutzungsplanung_V1_2.Catalogue_CH.Catalogue_CH TID="ch.admin.are.nutzungsplanung_catalogue_ch.12">
...
      </Nutzungsplanung_V1_2.Catalogue_CH.Catalogue_CH>

**Comment by kglaus** [comment]
@claeis 

Könntest du bitte auch direkt ili2pg anpassen, falls das Problem auch da vorkommen kann.

**Comment by kglaus** [comment]
@claeis 

Wie ist der Stand der Dinge bezüglich dieses Fehlers?
