### ISSUE TITLE
Aufbau der Meldungen im Log-File

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#362]
Soweit ich das sehe hat der Aufbau der Log-Meldungen eine strikte Struktur, basierend auf dem Trenner Doppelpunkt ":" und trennt klar wiederholende Texte und Objektinformationen.

Bei den "unique constraints" gibt es aber eine Abweichung - im letzten Zeilenteil mischen sich diese Texttypen ohne Doppelpunkt:

`Error: line 1102061: DSS_2015_LV95.Siedlungsentwaesserung.Einzelflaeche: tid ch123w2abcdefg: Unique constraint DSS_2015_LV95.Siedlungsentwaesserung.Einzelflaeche.Constraint1 is violated! Values Rinne, Politische Gemeinde Test already exist in Object: ch123w2m854TBz44
`
Ist das so beabsichtigt?

**Comment by beistehen** [comment]
Was ist der Anwendungsfall, wo du dich daran störst, dass die Unique constraints Fehlermeldung anders ist als die anderen Fehlermeldungen? Und wie müsste die Meldung deiner Meinung nach aussehen?

**Comment by Pierre-de-la-Verre** [comment]
Die Idee dahinter (der Anwendungsfall) ist, aus dem Fehlerprotokoll einen Überblick über die Fehlertypen und deren Anzahl zu erstellen. Ich habe mir etwas gebastelt, das die Logs durchgeht, jede ERROR Zeile an den Doppelpunkten zerlegt und den letzten Wert zählt. Da kommt dann sowas raus:

*********************************
Mittwoch, 26.Oktober 2022; 17:07:39
Prüfdatei: d:\test\map\aw23e.log

```
2	 AbwasserbauwerkRef should associate 1 to 1 target objects (instead of 0)
2	 AbwasserknotenRef should associate 1 to 1 target objects (instead of 0)
47	 Attribute Bezeichnung is length restricted to 20
28	 Mandatory Constraint DSS_2015_LV95.Siedlungsentwaesserung.Abwassernetzelement.Constraint1 is not true.
4	 Mandatory Constraint DSS_2015_LV95.Siedlungsentwaesserung.Anschlussobjekt.Constraint1 is not true.
1	 Mandatory Constraint DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet.Constraint1 is not true.
3	 Mandatory Constraint DSS_2015_LV95.Siedlungsentwaesserung.Haltung.Constraint2 is not true.
3	 Mandatory Constraint DSS_2015_LV95.Siedlungsentwaesserung.Haltung.Constraint3 is not true.
2	 Mandatory Constraint DSS_2015_LV95.Siedlungsentwaesserung.Spezialbauwerk.Constraint3 is not true.
9	 value SAA.Sammelkanal is not a member of the enumeration in attribute FunktionHierarchisch
```

Beim obigen Beispiel ist der letzte Wert wegen der Objektinformation jeweils einmalig, daher kann die eigentliche Fehlermeldung "Unique constraint DSS_2015_LV95.Siedlungsentwaesserung.Abwasserknoten.Constraint1 is violated! " nicht hochgezählt werden.

Wie soll es aussehen?
Gute Frage. Wenn der Validator (optional) diese Zusammenfassung machen würde ist das Thema hinfällig. Aber im Detail kann ich es nicht definieren, pauschal wäre eine vollständig auswertbare Struktur schön.

**Comment by edigonzales** [comment]
> Wie soll es aussehen? Gute Frage. Wenn der Validator (optional) diese Zusammenfassung machen würde ist das Thema hinfällig. Aber im Detail kann ich es nicht definieren, pauschal wäre eine vollständig auswertbare Struktur schön.

`--xtflog file         INTERLIS transfer file, that receives validation results.`


Modell: https://models.interlis.ch/tools/IliVErrors.ili

**Comment by Pierre-de-la-Verre** [comment]
Wenn ich das richtig sehe stehen auch dort die gleichen Meldungen, aber eben anders formatiert. Aber wenn das keinen allgemeinen Nutzen bringt kann ich auch mit der Situation leben.

**Comment by edigonzales** [comment]
"auswertbare Struktur": Ich habs jetzt nicht verglichen. Aber das XTF-Log ist jedenfalls strukturierter. Aber in diesem Fall trotzdem "falsch"?

**Comment by Pierre-de-la-Verre** [comment]
"falsch" ist nicht korrekt, aber der oben zitierte Satz mit der Mischung der Daten steht genauso drinnen.

**Comment by claeis** [comment]
Oft versteht man die Meldungen deutlich besser, wenn man gewisse Daten in die Fehlermeldungen (im engeren Sinn) packt (bei UNIQUE eben z.B. die Werte die doppelt vorkommen). Darum ist nicht alles strukturiert. Um das alles zu  strukturieren bräuchte es ein komplexeres IliVErrors.ili

Aber grundsätzlich finde ich es falsch, eine Statistik der Fehlermeldungen zu erstellen. Weil es oft Fehlersituationen gibt, die zu Folgefehlermeldungen führen, oder die Validierungslogik ausschalten um Folgefehlermeldungen zu vermeiden. Also Beides Dinge, die eine Fehlermeldungsstatistik total verfälschen.

**Comment by Pierre-de-la-Verre** [comment]
Es ist ja nicht für "offiziellen" Einsatz, gedacht, aber es gibt etwas Überblick, wieviel von welchen Fehlern da ist und welche Arbeit einen noch zur Korrektur erwartet.
Danke für die Rückmeldungen.
