### ISSUE TITLE
--verbose Option

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#365]
Die --verbose-Option funktioniert nicht. 

```
java -jar Downloads/ilivalidator-1.12.1/ilivalidator-1.12.1.jar --verbose Downloads/ch.so.avt.kantonsstrassen_xtf/ch.so.avt.kantonsstrassen.xtf
```

liefert:

```
ilivalidator: wrong number of arguments
```

ilivalidator 1.12.1 unter Windows.

**Comment by olivergrimm** [comment]
Mit
`-verbose True`
wird das Argument akzeptiert. Ich schaus aber morgen noch mit @patrickackermann an und liefere dir noch etwas qualifiziertere Infos.
