### ISSUE TITLE
ILI 2 accept valid AREA overlaps

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#366]
Beiliegendes Beispiel [ZoPla_IlivalidatorTest.zip](https://github.com/claeis/ilivalidator/files/10140662/ZoPla_IlivalidatorTest.zip) enthält drei Flächen, wo der ilivalidator viermal einen "Intersection overlap" meldet. Beim Darstellen dieser Geometrien mit FME ist auch bei maximalem Zoom keine Überschneidung feststellbar. Gemäss Modell (das für die Geometrie das entsprechende Basismodul des Bundes importiert) beträgt die tolerierte Überlappung 1mm oder kleiner.

**Comment by edigonzales** [comment]
Ich habe die Daten mit ili2gpkg umgewandelt und dabei die Kreisbogen nicht segmentiert. An besagter Stelle _sehe_ ich einen Overlap. Siehe georeferenziertes PNG im Zipfile.

[Archive.zip](https://github.com/claeis/ilivalidator/files/10141413/Archive.zip)


![intersection](https://user-images.githubusercontent.com/2767800/205303573-cc85f772-a2f0-4f1a-b51b-0fead31c21ab.png)

```
java -jar /Users/stefan/apps/ili2gpkg-4.8.0/ili2gpkg-4.8.0.jar --dbfile fubar2.gpkg --disableValidation --defaultSrsCode 2056 --models Nutzungsplanung_V310 --modeldir ".;https://models.geo.admin.ch" --doSchemaImport --import ZoPla_IlivalidatorTest.XTF
```

**Comment by claeis** [comment]
Das ist kein kleines Problem. Die Art und Weise, wie AREA in Ili 2 geprüft wird, muss überarbeitet werden. Bei SURFACE wird eine solcher Overlap korrekt entfernt/bereinigt. Bei AREA muss das aber anders gemacht werden, und zwar so, dass beide an die zu korrigierende Randlinie anstossenden Polygone gleich korrigiert werden.

**Comment by claeis** [comment]
Betrifft auch INTERLIS.areAreas()
