### ISSUE TITLE
Unique constraint not checked

### ISSUE THREAD

**Issue by leader80** [claeis/ilivalidator#37]
Hi, 

we are not able to check the UNIQUE constraint of our model:
[2 - Schutzbauten_V05_zweite_Anhörung.ili.txt](https://github.com/claeis/ilivalidator/files/828174/2.-.Schutzbauten_V05_zweite_Anhorung.ili.txt)

[export_ch.xtf.txt](https://github.com/claeis/ilivalidator/files/828184/export_ch.xtf.txt)

we are not getting any warning for the duplicated <Schutzbauten_ID>RM011</Schutzbauten_ID> which is a unique constraint.

Thanks
G.

**Comment by claeis** [comment]
fixed in 1.0.0

**Comment by giodegiorgi** [comment]
Great! Thanks nice job!
