### ISSUE TITLE
RFE - Error message meaningfull

### ISSUE THREAD

**Issue by giodegiorgi** [claeis/ilivalidator#38]
Dear all,

we have a request for enhancement, is it possible to have a better error message, or at least a clearer information to understand the validation problem?

For example the following code is missing the Geometry:

`<Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt TID="11"><Datenherr>Kantone.AI</Datenherr><Schutzbauten_ID>22</Schutzbauten_ID><Aggregierung>Einzelwerk</Aggregierung><Hauptprozess>Wasser</Hauptprozess><weiterer_Prozess_Wasser>false</weiterer_Prozess_Wasser><weiterer_Prozess_Rutschung>false</weiterer_Prozess_Rutschung><weiterer_Prozess_Sturz>true</weiterer_Prozess_Sturz><weiterer_Prozess_Lawine>false</weiterer_Prozess_Lawine><Werksart>Wasser.Entlastung.Entlastungsbauwerk</Werksart><Material>Beton</Material><Laenge>22</Laenge><Breite>22.0</Breite><Hoehe>22.0</Hoehe><Hoehe_zum_Umland>22.0</Hoehe_zum_Umland><Flaeche>22</Flaeche><Rueckhaltevolumen>22</Rueckhaltevolumen><Anzahl>22</Anzahl><Gesamtlaenge>22</Gesamtlaenge><Gesamtflaeche>22</Gesamtflaeche><Erstellungsjahr>2010</Erstellungsjahr><Erhaltungsverantwortung_Kategorie>ASTRA</Erhaltungsverantwortung_Kategorie><Erhaltungsverantwortung_Name>ok</Erhaltungsverantwortung_Name><Zustand>alarmierend</Zustand><Zustandsbeurteilung_Jahr>2015</Zustandsbeurteilung_Jahr><Bemerkungen>asd</Bemerkungen></Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt>
`
[export_ch.xtf.txt](https://github.com/claeis/ilivalidator/files/833918/export_ch.xtf.txt)

But the error message is just saying:

`Error: line 14: Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt: tid 11: Mandatory Constraint Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint2 is not true.`

Constraint2 is not true... Actually is missing a parameter.
Could we have a bettere error message?

Bests
G

**Comment by giodegiorgi** [comment]
Do I have to map all the possible constrain issues? how do you know how it is associated to the ili model?

**Comment by claeis** [comment]
The name of the section in the toml file is the qualified name of the interlis model element (in this case ``Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt.Constraint2`` is in the model ``Schutzbauten_LV03_V05`` in the topic ``Schutzbauten`` in the class ``Schutzbautenobjekt`` the constraint ``Constraint2``).

**Comment by giodegiorgi** [comment]
okay, but which one is the Constraint2? in the ili there isn't any reference.

**Comment by claeis** [comment]
counted per class/from top to bottom. If you own the model/ili, you can also add a name by adding the comment before the constraint

    ``!!@name=mynameoftheconstraint``
    MANDATORY CONSTRAINT ....;
