### ISSUE TITLE
new option --csvlog

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#403]
Wie `--xtflog`, jedoch Ausgabe als csv auf Basis Modell _IliVErrors_.

**Comment by claeis** [comment]
Ist xtflog nicht einfach genug?

CSV ist längerfristig immer problematisch/Support anfällig...welches Character-Encoding? welches Trennzeichen? und wie geht man mit Werten um, die das Trennzeichen enthalten? Alles Probleme, die man mit XML nicht hat.

**Comment by beistehen** [comment]
Aktueller Workflow ist dieser:

1. ilivalidator macht xtflog
2. ili2db macht aus xtflog Tabelle in DB
3. Tabelle aus DB exportieren als csv (Datei oder Zwischenablage)
4. csv in Excel einlesen und auswerten

Praktisch wäre, wenn man das abkürzen könnte. Einem Endnutzer ist das nicht zumutbar. Hast du einen Vorschlag wie?

> ...welches Character-Encoding? welches Trennzeichen? und wie geht man mit Werten um, die das Trennzeichen enthalten?

Default-Werte annehmen, die via (Meta)config übersteuert werden können?

**Comment by edigonzales** [comment]
Wäre --xlslog nicht angebrachter?

- Leute, die CSV wollen, wollen eigentlich XLS
- Leute, die nicht XLS wollen, wollen auch nicht CSV, sondern können mit Standard-Output und/oder XTF umgehen
- Keine Diskussion bezüglich Encoding, Trennzeichen etc.

Weil Weihnachten vor der Türe steht: Plugin-Mechanismus. Man schreibt sein eigenes, zusätzliches Output-Format und schmeisst das Jar in den Plugin-Ordner. Auftraggeber kann bei Bedarf an seine Kunden ein eigenes ilivalidator-Paket schnüren, inkl. Custom-Logformat und Validierungsfunktionen.

**Comment by beistehen** [comment]
Vielleicht kann es wirklich direkt xlsx sein. Das ist auch XML.

Wäre das eine passende Library?
https://github.com/dhatim/fastexcel

**Comment by claeis** [comment]
Bitte verifizieren

**Comment by beistehen** [comment]
> Bitte verifizieren

Erste Tests sind erfolgreich, vielen Dank!

Feststellungen:
a)
Double quote `"` zur Abgrenzung von Text macht beim Öffnen des csv mit Excel Probleme, weil ein solches Zeichen zu Beginn einer Zelle entfernt wird. Danach werden die Spalten nicht mehr an der richtigen Stelle getrennt, wenn im Text Kommas vorhanden sind.
Abhilfe schafft das Ändern der Textabgrenzung auf single quote `'`; diese werden beim Öffnen des csv nicht entfernt.

b)
--xtflog erzeugt ein xtf in UTF-8 *ohne* BOM
--csvlog erzeugt ein csv in UTF-8 *mit* BOM

Lässt sich das vereinheitlichen (am liebsten beide ohne BOM)?

Nachtrag: habe soeben die Korrektur in iox-ili auf [csv-Export *mit* BOM gesehen](https://github.com/claeis/iox-ili/commit/b3386998061438e9fad89293fbdbb1969c40b054) entdeckt. Meine Tests (csv mit/ohne BOM) zeigen, dass der Unterschied nur im Verhalten von Excel ändert: mit BOM wird ein zusätzlicher Import-Dialog angezeigt; ohne BOM wird dieser Dialog nicht angezeigt. Ist das der einzige Grund, weshalb aktuell das csv mit BOM exportiert wird?
