### ISSUE TITLE
Abwasser must be declared as ABSTRACT. One of its elements (Organisation) is abstract.

### ISSUE THREAD

**Issue by PeterZamudio** [claeis/ilivalidator#410]
Hello everyone

I am strangely suddenly getting this error on all Abwasser data. can anyone help on where the problem is?
Do I need to alter the ili-file or is there a problem in the data with Organisations that have no data?

Error: k:\ITF-EXPORT\SIA405_ABWASSER_2015_LV95.ili:37:SIA405_ABWASSER_2015_LV95.SIA405_Abwasser must be declared as ABSTRACT. One of its elements (Organisation) is abstract.

Best regards
Peter Zamudio

**Comment by beistehen** [comment]
Is there a difference between your model and the official one at https://405.sia.ch/models/2015/ ?

**Comment by PeterZamudio** [comment]
Thank you, you put me on the right track there. The files were not the same. Strange is the export had worked fine the last 2 years. But the two file did have lots of differences.(not from me) I hid my old ili and copied the SIA405_Abwasser_2015_2_d-20180417.ili into my models dir. And bingo it worked again.
Thank you very much for that.

**Comment by PeterZamudio** [comment]
Great when we can help each other, thanks.
