### ISSUE TITLE
Offizieller Release 1.14.2

### ISSUE THREAD

**Issue by beistehen** [claeis/ilivalidator#411]
Gemäss [CHANGELOG.txt](https://github.com/claeis/ilivalidator/blob/master/docs/CHANGELOG.txt) wurde v1.14.2 am 01.05.2024 released. Diese Version ist jedoch nicht unter https://downloads.interlis.ch verfügbar und erscheint deshalb auch nicht auf interlis.ch.

**Comment by Pierre-de-la-Verre** [comment]
ich vermisse auch den Hinweis, dass
"GUI: skip logging errors to log window if to many errors (#259) vom 29.12.2023"
jetzt auch wirklich funktioniert.
(Ich finde so auf die schnelle den richtigen Beitrag nicht dazu - werde ihn nachliefern)
