### ISSUE TITLE
Endlose Validierung aufgrund Objekten ohne Geometrien?

### ISSUE THREAD

**Issue by dkottmann** [claeis/ilivalidator#413]
Hier eine Fehlermeldung betreffend ilivalidator 1.14.2 vom Kanton Thurgau: 

> Wir haben anfangs der Woche neue Daten zum Thema Waldgrenzen auf Intergration und Produktion von geodienste.ch hochgeladen. Die Daten können jedoch nicht vom ilivalidator geprüft werden. Der ilivalidator prüft scheinbar endlos und wirft auch keine Fehlermeldung (auch lokal mit der Version 1.14.2 getestet). Grund dafür sind Objekte ohne Geometrien.
> 
> Allenfalls müsste auch der ilivalidator angepasst werden, damit er solche Datenprüfungen mit Fehlern abbricht. Ihr könnt dazu gerne unsere Daten fürs Debugging nutzen.

Daten für das Debugging hier: 
[wg_tg.zip](https://github.com/user-attachments/files/16379076/wg_tg.zip)

**Comment by edigonzales** [comment]
Eventuell gleicher Bug: https://github.com/claeis/ilivalidator/issues/216

**Comment by claeis** [comment]
fixed with c3b99887c693ae449ff85d0af94ecb6f736efa59
