### ISSUE TITLE
INTERLIS 2.2 Dateien können nicht mehr validiert werden

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#431]
[error_VOLLZUG_SO0300002511_1153_20210329115028.xml.zip](https://github.com/user-attachments/files/18006028/error_VOLLZUG_SO0300002511_1153_20210329115028.xml.zip)

```
java -jar livalidator-1.14.4.jar error_VOLLZUG_SO0300002511_1153_20210329115028.xml
```

```

Info: ilivalidator-1.14.4-81646d01b5b2e5713e864e300c44c05e8c79b437
Info: ili2c-5.6.2-98609b0574483403389e1c914bc928155d59fdea
Info: iox-ili-1.23.3-fad31de1519aac5c06d1c5f41e021b8608c744d3
Info: java.version 21.0.2
Info: User <stefan>
Info: Start date 2024-12-04 10:56
Info: maxMemory 6291456 KB
Info: dataFile <error_VOLLZUG_SO0300002511_1153_20210329115028.xml>
Info: pluginFolder </Users/stefan/apps/ilivalidator-1.14.4/plugins>
Info: modeldir <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels>
Warning: failed to get modelnames from transferfile (ch.interlis.iox_j.IoxSyntaxException: Unexpected XML event ALIAS found.)
Warning: failed to get version from data file; ch.interlis.iox_j.IoxSyntaxException: Unexpected XML event ALIAS found.; ignored
Error: no models given to look for
```

**Comment by olivergrimm** [comment]
Der folgende Header-Comment verursacht seit 1.14.4 eine analoge Meldung und scheint auch mit 1.14.5-SNAPSHOT nicht gelöst zu sein:
```
  <HEADERSECTION VERSION="2.3" SENDER="UNKNOWN">
    <MODELS>
      <MODEL NAME="SIA405_LKMap_2015_LV95" URI="http://www.sia.ch/405" VERSION="27.04.2018" />
    </MODELS>
    <ALIAS>
      <ENTRIES FOR="SIA405_LKMap_2015_LV95">
      </ENTRIES>
    </ALIAS>
    <COMMENT>
      dataset generated by xtfout version 1.5, (c) infoGrips GmbH 2005-2022
    </COMMENT>
  </HEADERSECTION>
  ```

Fehler:

`Warning: failed to get version from data file; ch.interlis.iox_j.IoxSyntaxException: Unexpected XML event COMMENT found.; ignored
Error: no models given to look for
Error:     ch.interlis.ilirepository.IliManager.getConfig(IliManager.java:287)
Error:     ch.interlis.ilirepository.IliManager.getConfig(IliManager.java:280)
Error:     org.interlis2.validator.Validator.compileIli(Validator.java:680)
Error:     org.interlis2.validator.Validator.validate(Validator.java:355)
Error:     org.interlis2.validator.Validator.runValidation(Validator.java:82)
Error:     org.interlis2.validator.Main.main(Main.java:216)`

Wenn ich das COMMENT-Element lösche, klappt die Datei-Interpretation

**Comment by olivergrimm** [comment]
@claeis Aus meiner Sicht muss dieser Issue nochmals geöffnet werden. Das Parsen von COMMENT-Einträgen schlägt seit 1.14.4 fehl.

**Comment by claeis** [comment]
Funktioniert mit dem https://jars.interlis.ch/ch/interlis/ilivalidator/1.14.5-SNAPSHOT/ilivalidator-1.14.5-20241206.080626-3-bindist.zip wie erwartet!?

**Comment by uebeee** [comment]
Die Validierung funktioniert nun auch mit COMMENT-Element im xtf mit ilivalidator-1.14.5. Besten Dank!

**Comment by olivergrimm** [comment]
> Funktioniert mit dem https://jars.interlis.ch/ch/interlis/ilivalidator/1.14.5-SNAPSHOT/ilivalidator-1.14.5-20241206.080626-3-bindist.zip wie erwartet!?

Mit den folgenden Versionen scheiterte die Validierung auf alle Fälle:
```
PS C:\Program Files\INTERLIS\ilivalidator> java -jar .\ilivalidator-1.14.5-SNAPSHOT.jar "D:\_TASKS\ch.swisstopo.lk2dxf\ckw-kulm_ele.xtf"
**Info: ilivalidator-1.14.5-SNAPSHOT-d021297c9a08fa7af2aaccce0998003684b8d4ca**
Info: ili2c-5.6.2-98609b0574483403389e1c914bc928155d59fdea
Info: iox-ili-1.23.3-fad31de1519aac5c06d1c5f41e021b8608c744d3
Info: java.version 21.0.1
Info: User <ogrimm>
Info: Start date 2025-01-10 08:36
Info: maxMemory 8339456 KB
Info: dataFile <D:\_TASKS\ch.swisstopo.lk2dxf\ckw-kulm_ele.xtf>
Info: pluginFolder <C:\Program Files\INTERLIS\ilivalidator\.\plugins>
Info: modeldir <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels>
Warning: failed to get modelnames from transferfile (ch.interlis.iox_j.IoxSyntaxException: Unexpected XML event COMMENT found.)
Warning: failed to get version from data file; ch.interlis.iox_j.IoxSyntaxException: Unexpected XML event COMMENT found.; ignored
Error: no models given to look for
```

Wenn ich die am 6.1.25 releaste 1.14.5-SNAPSHOT-Version teste, dann klappts.
