### ISSUE TITLE
Custom messages in toml are not respected

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#48]
If I downgrade a multiplicity constraint from error to a warning for a specific attribute in the toml file and define a custom`msg`, the message is not used.

Using todays master of iox-ili and ilivalidator.
[Archive.zip](https://github.com/claeis/ilivalidator/files/922402/Archive.zip)

**Comment by claeis** [comment]
Custom message support is only for constraints (and not for "type" or "multiplicity" validations)
