### ISSUE TITLE
INTERLIS.areAreas() not finding overlap

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#50]
See attached example. Overlap is at:

`                <COORD>
                  <C1>2611525.183842287</C1>
                  <C2>1233940.2942460973</C2>
                </COORD>`

[Archive.zip](https://github.com/claeis/ilivalidator/files/924348/Archive.zip)

**Comment by claeis** [comment]
Please report only one problem per issue

**Comment by claeis** [comment]
see claeis/iox-ili#16

**Comment by claeis** [comment]
see claeis/iox-ili#37
