### ISSUE TITLE
Missing coordinate in xtflog for errors detected by a custom function

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#51]
There are no coordinates written in the xtflog if the errors are detected by custom functions implementing the InterlisFunction interface.

See attached xtf logfile ("Projektierte Gebaeude duerfen hoechstens 3 Jahre alt sein.").

The class I validate has a surface geometry so I'm not sure if it only reports coordinates from point geometries.

[fubar1.xtf.zip](https://github.com/claeis/ilivalidator/files/924448/fubar1.xtf.zip)

**Comment by claeis** [comment]
Please add the model to the issue. Is the error reported by the custom function?
