### ISSUE TITLE
INTERLIS.areAreas() performance

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#56]
Not sure if it's related to the other `INTERLIS.areAreas()` tickets or even relevant: [https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1377](https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Validator.java#L1377) is called multiple times. `polygonPool.getLines().size()` is the same for every call.

**Comment by claeis** [comment]
pls re-open, if you think the problem still exists
