### ISSUE TITLE
Fail to validate test data

### ISSUE THREAD

**Issue by pvalsecc** [claeis/ilivalidator#61]
If you try to validate Test23_gr.xtf from http://www.interlis.ch/interlis2/docs23/test23_20150413.zip with ilivalidator v1.2.1, you get this error:

```
Info: ilivalidator-1.2.1-20170420
Info: ili2c-4.7.2-20170413
Info: iox-ili-1.18.1-master-20170420
Info: maxMemory 3568128 KB
Info: xtfFile </data/input/Test23_gr.xtf>
Info: pluginFolder </ilivalidator/plugins>
Info: ilidirs </data/models;/models;%ILI_FROM_DB;%XTF_DIR;http://models.interlis.ch/;%JAR_DIR>
Info: lookup model <Test23_gr> in repository </data/models>
Info: lookup model <Test23> 2.3 in repository </data/models>
Info: lookup model <Time> 2.3 in repository </data/models>
Info: lookup model <Units> 2.3 in repository </data/models>
Info: ilifile </data/models/Units-20120220.ili>
Info: ilifile </data/models/Time-20050616.ili>
Info: ilifile </data/models/Test23.ili>
Info: ilifile </data/models/Test23_gr.ili>
Error: /data/models/Test23_gr.ili:664:STRUCTURE attribute Pos not allowed in UniquenessConstraint.
Error: compiler failed
```

**Comment by beistehen** [comment]
This is not an error concerning ilivalidator but INTERLIS compiler ([ili2c](http://interlis.ch/interlis2/download23_e.php)). It says that the model syntax is wrong. This makes ilivalidator not even start the validation process.

As ili2c has evolved in time, this model has passed the compiler error-free in 2015 but doesn't pass it with the actual version of the compiler (see line 2 in the logfile: ili2c-4.7.2-20170413).

Obviously the UniquenessConstraint with structures wasn't thoroughly checked with older versions of ili2c. So you can change line 664 in Test23_gr.ili

from
`UNIQUE Pos;`

to
`UNIQUE (LOCAL) Pos : Groesse;`

and the model will compile without errors. This should result in the validation process beeing run when you start ilivalidator again.

Regards,
Stefan

PS. The test data and models on interlis.ch are going to be renewed anytime soon.
