### ISSUE TITLE
Numerical AREA overlap issue

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#62]
Die Flurnamen (DM01) wurden mit ili2pg in die Datenbank importiert (`--strokeArcs`) und anschliessend mit SQL in ein anderes Modell umgebaut. Die Geometrien werden bis auf `ST_Force3D()` nicht verändert. Die Prüfung des neuen INTERLIS-Transferfiles scheitert an einem Overlap:

`Error: intersection tid1 55f5f18b-2ed2-4d2d-b8c3-6deffbefe75e, tid2 67aca7e5-08d7-4fcd-979f-f0512f41f7da, coord (2613109.5287728338, 1224224.2445313344, NaN)
Info: validateAllAreas(): overlap null, seg1 (2613109.4229093385 1224224.4082201498, 2613109.5630057147 1224224.1915995872), seg2 (2613109.5630057147 1224224.1915995874, 2613109.422909338 1224224.4082201498) (Validator.java:341)
Error: line 48: DMCSCHLN_20170503.Local_names.Local_geographical_name: tid 79dbae35-ff74-4faa-9e83-5dc43a5d9f02: failed to validate AREA DMCSCHLN_20170503.Local_names.Local_geographical_name.Geometry`

Erst weit hinter dem Komma gibt es Unterschiede.

[Archive.zip](https://github.com/claeis/ilivalidator/files/981052/Archive.zip)

**Comment by edigonzales** [comment]
`ST_SnapToGrid(..., 0.00001)` "löst" das Problem.

**Comment by claeis** [comment]
see also #111
