### ISSUE TITLE
AREA validation error (reporting)

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#65]
ilivalidator reports some intersection errors with coordinates that do not exist in the XTF (attached). It seems it has something to do with arcs...

`Info: validate AREA SO_Nutzungsplanung_20170105.Nutzungsplanung.Grundnutzung.Geometrie...
Error: intersection tid1 null, tid2 null, coord (2619428.051, 1257985.691, NaN), coord2 (2619428.04084922, 1257985.689877912, NaN)`

`coord2` does not exist in the XTF. 

[145_NPL_SO_32_0_LV95_bid_fix.XTF.zip](https://github.com/claeis/ilivalidator/files/1016264/145_NPL_SO_32_0_LV95_bid_fix.XTF.zip)

**Comment by edigonzales** [comment]
Find same behaviour with this data.
[npl_niederbuchsiten.zip](https://github.com/claeis/ilivalidator/files/1128943/npl_niederbuchsiten.zip)

At `Error: intersection tid1 null, tid2 null, coord (2625285.589, 1238688.269, NaN), coord2 (2625285.3554505454, 1238688.1325746486, NaN)` I don't see any error.

`Error: intersection tid1 null, tid2 null, coord (2625227.875, 1239015.03, NaN), coord2 (2625228.244658479, 1239014.2915069729, NaN)` is kinda ugly geometry. Not sure if it's an error though.

**Comment by claeis** [comment]
the reported coordinate is the intersection point and not a boundary vertex. 

The problematic objects in ```npl_niederbuchsiten.xml``` are ```3f118fd3-5977-46ed-b4d7-faacaf271387``` and ```3f118fd3-5977-46ed-b4d7-faacaf213226```.

The report message needs to be improved (should include the affected tid).

**Comment by claeis** [comment]
Intersection overlap 0.0015502480878408775, coord1 (2625285.589, 1238688.269, NaN), coord2 (2625285.3554505454, 1238688.1325746486, NaN), tid1 3f118fd3-5977-46ed-b4d7-faacaf213222, tid2 3f118fd3-5977-46ed-b4d7-faacaf271374
