### ISSUE TITLE
Problem with checking Constraint

### ISSUE THREAD

**Issue by romefi** [claeis/ilivalidator#67]
Bei unserer Gefahrenkarte wird im ilivalidator (Version 1.2.1) ein Constraint-Fehler ausgegeben. Der iG/Check gibt keinen Fehler aus. Meiner Ansicht nach sollten im XTF alle Constraints erfüllt sein. Könnte das ein Bug im ilivalidator sein? Oder übersehe ich einen Fehler in den Daten?

XTF, Log und Modell: 
[hazard_mapping.zip](https://github.com/claeis/ilivalidator/files/1046763/hazard_mapping.zip)

**Comment by edigonzales** [comment]
Mein kurzes Debugging hat ergeben, dass ilivalidator über `(return_period_in_years > 300)` stolpert. Alle anderen Constraint-Prüfungen funktionieren.

ilivalidator kann die DOMAIN nicht mit 300 vergleichen. Ersetzt man `return_period_in_years: return_period_type` mit `return_period_in_years: 1..1000` funktionierts wieder.

Gefühlt irgendwo hier sollte der Vergleich stattfinden: [https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Value.java#L190](https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Value.java#L190), was nicht passiert und zur Exception führt: [https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Value.java#L225](https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Value.java#L225)
