### ISSUE TITLE
Error message doItfOidPerTable!=false

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#70]
Beim Prüfen von ÖREB-Daten gemäss neuem Rahmenmodell erscheint untenstehende Fehlermeldung:
...
Info: validate data...
Info: first validation pass...
Error: doItfOidPerTable!=false
Info: ...validation failed

**Comment by edigonzales** [comment]
Any data you can provide?

**Comment by edigonzales** [comment]
Works for me.

`java -jar /home/stefan/Apps/ilivalidator-1.2.1/ilivalidator.jar --log oereb-bazl.log ch.bazl.sicherheitszonenplan.oereb_20131118.xtf`

Make sure that `ilivalidator` does not get confused by other `ili` or `xtf` files in the same directory. Or in other words: copy the xtf in a directory with nothing else in it. Delete your `.ilicache` directory. On Linux: `/home/stefan/.ilicache`.

[oereb-bazl.log.zip](https://github.com/claeis/ilivalidator/files/1071702/oereb-bazl.log.zip)

**Comment by claeis** [comment]
Problem is, that some transient settings are save to $HOME/.ilivalidator
