### ISSUE TITLE
support remote Catalogues

### ISSUE THREAD

**Issue by claeis** [claeis/ilivalidator#71]

**Comment by m-kuhn** [comment]
Is there a prototype available?

**Comment by claeis** [comment]
no code yet. The draft model for ilidata.xml is [here](https://github.com/claeis/ili2c/blob/master/standard/DataIdx16.ili)

**Comment by claeis** [comment]
and meta attribute ```limitedTo``` to defined a restriction to some basket. See models LegendeEintrag_PlanGewaesserschutz_V1_1, WZVV_Codelisten_V1_2 for an example.

**Comment by claeis** [comment]
see https://github.com/claeis/ili2c/blob/master/test/data/listdata/repos1/ilidata.xml for a sample

**Comment by m-kuhn** [comment]
@claeis is the structure of the xml finalized?

**Comment by claeis** [comment]
One real world test is pending, and then I will release it.
