### ISSUE TITLE
Multiplicity validation 

### ISSUE THREAD

**Issue by p1d1d1** [claeis/ilivalidator#73]
Doesn't seem to correctly validate multiplicity.
Tested with Beispiel2refOK.xtf:

- change REF="10" to REF="9" in object with TID="101" --> no error is reported
- should report an error since multiplicity of role Detail is 0..1, so 2 GebaueudeDetail cannot refer the same Gebaeude

or am I missing something?

**Comment by claeis** [comment]
EXTERNAL indicates that the referenced objects are in a different basket (even outside of the same file). The validator doesn't know, that he has access to all objects, therefore he assumes that these references reference objects to which he has no access. He can not check the cardinality (or that the object even exists). see #78
