### ISSUE TITLE
Wrong error log message

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#74]
`Error: line 25836: SO_Nutzungsplanung_20170105.Nutzungsplanung.Ueberlagernd_Flaeche: tid 3f118fd3-5977-46ed-b4d7-faacaf215997: failed to validate AREA SO_Nutzungsplanung_20170105.Nutzungsplanung.Grundnutzung.Geometrie`

As far as I understand this does not make any sense. Attached the data.
[npl_niederbuchsiten.zip](https://github.com/claeis/ilivalidator/files/1128940/npl_niederbuchsiten.zip)

**Comment by claeis** [comment]
commit claeis/iox-ili@f7db082e9fda1d58c9390c751a8b21643f4522c is erroneously related to this issue, should really by assigned to #62
