### ISSUE TITLE
function isEnumSubVal

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#76]
[isEnumSubVal.zip](https://github.com/claeis/ilivalidator/files/1193930/isEnumSubVal.zip)

Ist die Funktion isEnumSubVal korrekt implementiert worden? Beiliegendes Modell mit Daten ergeben keine Fehlermeldung, obschon eine erwartet wird.

**Comment by beistehen** [comment]
Salü Rolf

Die Parameter in der Funktion `isEnumSubVal` sind vertauscht im ILI. Der Funktionsaufruf sollte lauten:

`isEnumSubVal (Attribut1,#rot)` (statt ~~`isEnumSubVal (#rot, Attribut1)`~~)

Dann klappts und der Datensatz mit tid=11 wird als Fehler gemeldet.

Gruss
Stefan
