### ISSUE TITLE
implicit integer casting

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#79]
`CLASS Typ_Grundnutzung`
`Code_kommunal : MANDATORY TEXT*12;`
`MANDATORY CONSTRAINT (Code_kommunal == 1111);`
`END Typ_Grundnutzung;`

Constraints works as expected w/o the quotation marks. Is this on purpose?

**Comment by claeis** [comment]
invalid model; should be detected by compiler (-> compiler issue)
