### ISSUE TITLE
mandatory constraint problems because of umlaut

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#80]
`CLASS Typ_Grundnutzung`
`Bezeichnung : MANDATORY TEXT*100;`
`MANDATORY CONSTRAINT (Bezeichnung == "Gewässer");`
`END Typ_Grundnutzung;`

Does not work as expected since ilivalidator raises errors even when `Bezeichnung` is "Gewässer".

**Comment by edigonzales** [comment]
Reload ili file in jedit with encoding = ISO-8859-1 works.

**Comment by claeis** [comment]
claeis/ili2c#14
