### ISSUE TITLE
Constraint name will not be shown if ilivalid.msg is defined

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#81]
`VIEW v_Control_point`
    	`PROJECTION OF AVLight.Control_points.Control_point;`
   ` =`
      `ALL OF Control_point;`
      `!!@ name = Punktnummer_Laenge`
      `!!@ ilivalid.msg = "Laenge der Punktenummer {Number} ist falsch. Erwartet wird 8."`
      `MANDATORY CONSTRAINT (INTERLIS.len (Number)) == 8;`
`END v_Control_point;`

Th constraint name will not be shown in the log file / stdout if ilivalid.msg is defined.

**Comment by claeis** [comment]
That is intentional to give the user full control over the message text.
