### ISSUE TITLE
"model-spanning" constraints

### ISSUE THREAD

**Issue by ltzur** [claeis/ilivalidator#84]
Basis bilden die beiden Modelle https://models.geo.admin.ch/BAV/replaced/Schienennetz_V1_2.ili  und https://models.geo.admin.ch/BAV/replaced/HaltestellenOeV_V1_2.ili und je ein dazugehörender Datensatz (s. .zip-Datei BAV.zip). Im Modell Schienennetz gibt es eine Konsistenzbedingung die fordert, dass der Wert des Attributs Nummer der Daten des Schienennetzes in den Daten der Haltestellen zwingend vorkommen muss.
Wenn ich die beiden .xtf-Dateien einzeln prüfe erhalte ich keine Fehlermeldung, was absolut korrekt ist. Wenn ich aber beide .xtf-Daten in den ilivalidator lade, die Checkbox "Datenumfang vollständig" aktiviere und validiere, sollte ich eine Fehlermeldung erhalten, weil die Nummer „1111111“ von Zeile 24764 der Datei „SN_MGDM_de_2016-12-11_zrh.xtf“ in der Datei „HST_MGDM_de_201
[BAV.zip](https://github.com/claeis/ilivalidator/files/1397335/BAV.zip)
6-12-11_zrh.xtf“ nicht vorkommt. Mit anderen Worten, Konsistenzbedingungen sollten auch dateiübergreifend funktionieren, wenn ich beide beteiligten Dateien gemeinsam prüfe.

**Comment by claeis** [comment]
Problem ist, dass die Konsistenzbedingungen die innerhalb einer STRUCTURE definiert sind, nicht validiert werden (und nicht die Modell/Basket übergreifende Prüfung).

**Comment by ltzur** [comment]
Damit bin ich einverstanden, ganz ähnlich hat auch Michael Germann argumentiert. Was heisst das nun konkret: Muss ich einen neuen Issue unter dem korrekten Titel erfassen oder wird dieser Mangel auch mit dieser Bezeichnung in absehbarer Zeit behoben?

**Comment by claeis** [comment]
1.6.0
