### ISSUE TITLE
Unique Constraint Performance

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#91]
Die Prüfung von circa 300 AV-ITF dauerte mit Version 1.0.0 circa 2 Stunden. Mit Version 1.5.0 circa 16 Stunden.

Ein möglicher Grund dürfte die Prüfung von Unique Constraints sein. Da gab es zwischen v1.0.0 und v1.5.0 eine Änderung: [ https://github.com/claeis/iox-ili/commit/c4441417c55dcc690a33109d11e875933be8cb5b]( https://github.com/claeis/iox-ili/commit/c4441417c55dcc690a33109d11e875933be8cb5b).

Auskommentieren von [https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Validator.java#L2515](https://github.com/claeis/iox-ili/blob/master/src/main/java/ch/interlis/iox_j/validator/Validator.java#L2515) macht das ganze wieder schneller.

Eventuell verschuldet durch die vielen get/puts mit vielen Objekten.

**Comment by claeis** [comment]
fixed in 1.6.0
