### ISSUE TITLE
allObjectsAccessible not working

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#92]
Gemäss Modell [http://geo.so.ch/models/ARP/SO_Nutzungsplanung_20170105.ili](http://geo.so.ch/models/ARP/SO_Nutzungsplanung_20170105.ili) und Assoziation `Dokument_Ueberlagernd_Flaeche` muss jedes Dokument mindestens einer überlagernden Fläche zugewiesen sein. Im angehängten XTF ist das nie der Fall jedoch findet ilivalidator trotz `--allObjectsAccessible` diesen Fehler nicht.

[roh_20170717A_export.xtf.zip](https://github.com/claeis/ilivalidator/files/1463640/roh_20170717A_export.xtf.zip)

**Comment by claeis** [comment]
fixed in 1.6.0
