### ISSUE TITLE
Check of transfer structure V1_1 (of KbS) crashes with Java-NullPointerException

### ISSUE THREAD

**Issue by pramisters** [claeis/ilivalidator#98]
See Log-File in ZIP.
Any ideas?
(iG/Check doesn't crash)

[OeREBKRMtrsfr_V1_1_KbS_2.zip](https://github.com/claeis/ilivalidator/files/1548234/OeREBKRMtrsfr_V1_1_KbS_2.zip)

**Comment by claeis** [comment]
OeREBKRMvs_V1_1.Vorschriften.Amt: tid amt290: Attribute Name requires a structure LocalisationCH_V1.MultilingualText

**Comment by claeis** [comment]
1.6.0
